/** العربية - vmesnik. Besedila strani ostanejo slovenska, dokler niso prevedena. */
export default {
  "jezik.naslov": "اللغة",
  "profil.aria": "الملف الشخصي",
  "meni.aria": "القائمة الرئيسية",
  "meni.arhiv": "الأرشيف",
  "meni.delo": "الأعمال",
  "meni.omeni": "عني",
  "meni.stik": "تواصل",
  "orodja.aria": "الأدوات",
  "orodja.iskanje": "بحث",
  "orodja.nastavitve": "الإعدادات",
  "orodja.arkada": "الألعاب",

  "nast.naslov": "الإعدادات",
  "nast.nazaj": "رجوع",
  "nast.zapri": "إغلاق",
  "nast.videz": "المظهر",
  "nast.jezik": "اللغة",
  "nast.prosojnost": "الشفافية",
  "nast.tema": "السمة",
  "nast.temna": "داكنة",
  "nast.svetla": "فاتحة",
  "nast.sistem": "حسب النظام",
  "nast.ozadje": "الخلفية",
  "nast.prizor": "المشهد",
  "nast.galaksija": "مجرة",
  "nast.zvezde": "نجوم فقط",
  "nast.izklop": "إيقاف",
  "nast.daljna": "مجرة بعيدة",
  "nast.daljnaOpis": "مجرة ثانية في الخلفية",
  "nast.galaksijaOpis": "التوهج، حجم النجوم، السرعة",
  "nast.gibanje": "الحركة",
  "nast.odziv": "الاستجابة للفأرة",
  "nast.odzivOpis": "العرض يتبع المؤشر",
  "nast.kazalec": "المؤشر",
  "nast.kazalecMeri": "مؤشر مخصص",
  "nast.kazalecMeriOpis": "شرارة بدلًا من مؤشر النظام",
  "nast.magnet": "أزرار مغناطيسية",
  "nast.magnetOpis": "تميل الأزرار نحو المؤشر",
  "nast.izris": "العرض",
  "nast.sij": "التوهج",
  "nast.velikost": "حجم النجوم",
  "nast.kamera": "الكاميرا",
  "nast.hitrost": "سرعة المدار",

  "zapis.zapri": "إغلاق",
  "zapis.prejsnja": "السابقة",
  "zapis.naslednja": "التالية",
  "zapis.odpri": "فتح التطبيق",
  "zapis.seVec": "والمزيد",
  "aplikacija.demo": "نسخة تجريبية · البيانات مختلقة",
  "aplikacija.zavihek": "فتح في علامة تبويب جديدة",
  "aplikacija.zapri": "إغلاق التطبيق",

  "viz.stran": "الموقع",
  "viz.prizor": "المشهد",
  "viz.prizorV": "مجرة، 50٬000 نقطة",
  "viz.izris": "العرض",
  "viz.izrisV": "WebGL، مظلّل خاص",
  "viz.ogrodje": "إطار العمل",
  "viz.ogrodjeV": "Vite، بلا إطار عمل",
  "viz.galerija": "المعرض",
  "viz.objav": "منشورات",
  "viz.maskota": "تميمة Jure Labs",
  "viz.zapri": "إغلاق بطاقة العمل",
  "viz.ascii": "رسوم ASCII متحركة من Jure Labs",
  "viz.metaT": "تطبيقات ويب حسب الطلب",
  "viz.metaS": "سريعة. موثوقة. فعّالة.",

  "kmeni.novZavihek": "فتح في علامة تبويب جديدة",
  "kmeni.kopiraj": "نسخ العنوان",
  "kmeni.profil": "الملف الشخصي",
  "kmeni.nastavitve": "الإعدادات",
  "kmeni.ponastavi": "إعادة ضبط العرض",
  "kmeni.kopirajBesedilo": "نسخ",
  "kmeni.kopirajPovezavo": "نسخ الرابط",
  "kmeni.kopirajEposto": "نسخ عنوان البريد الإلكتروني",
  "kmeni.odpriSliko": "فتح الصورة",
  "kmeni.kopirajSliko": "نسخ عنوان الصورة",
  "kmeni.jezik": "اللغة",
  "kmeni.kopirajStran": "نسخ رابط الصفحة",
  "kmeni.celozaslonsko": "ملء الشاشة",
  "kmeni.izhodCelozaslonsko": "الخروج من ملء الشاشة",
  "arkada.naslov": "الألعاب",
  "arkada.kmalu": "قريبًا",
  "arkada.opis": "الألعاب المصغّرة في الطريق. قريبًا ستتمكن من لعبها هنا.",

  "ogled.zapri": "إغلاق الصورة",
  "zemlja.slovenija": "سلوفينيا",

  "prof.zapri": "إغلاق",
  "prof.objav": "منشورات",
  "prof.sledilcev": "متابِعون",
  "prof.sledi": "يتابع",
  "prof.bio": "✨ إن لم ألتقط النجوم، سآتي من أجلك.",
  "prof.uredi": "تعديل الملف الشخصي",
  "prof.arhiv": "الأرشيف",
  "prof.objave": "المنشورات",
  "prof.shranjeno": "المحفوظات",
  "prof.oznaceno": "الإشارات",
  "prof.razporeditev": "التخطيط",

  "gal.razpored.tri": "ثلاثة أعمدة",
  "gal.razpored.dve": "عمودان",
  "gal.razpored.stiri": "أربعة أعمدة",
  "gal.razpored.mozaik": "فسيفساء",
  "gal.razpored.stopnice": "درجات",
  "gal.razpored.gost": "كثيف (6–7)",
  "gal.razpored.trak": "شريط",
  "gal.razpored.izvirno": "النسب الأصلية",
  "gal.razpored.izvirnoxl": "النسب الأصلية XL",
  "gal.razpored.polno": "ملء الشاشة",
  "gal.razpored.stolpci": "طوب",
  "gal.razpored.prostor": "مساحة ثلاثية الأبعاد",
  "gal.prostor.priblizaj": "تكبير",
  "gal.prostor.oddalji": "تصغير",
  "gal.razmik.da": "مع تباعد",
  "gal.razmik.ne": "بلا تباعد",
  "gal.sirina.robovi": "حتى الحواف",
  "gal.sirina.cez": "عريض",
  "gal.sirina.sredina": "في الوسط",
};
