/** Български - vmesnik. Besedila strani ostanejo slovenska, dokler niso prevedena. */
export default {
  "jezik.naslov": "Език",
  "profil.aria": "Профил",
  "meni.aria": "Главно меню",
  "meni.arhiv": "Архив",
  "meni.delo": "Работа",
  "meni.omeni": "За мен",
  "meni.stik": "Контакт",
  "orodja.aria": "Инструменти",
  "orodja.iskanje": "Търсене",
  "orodja.nastavitve": "Настройки",
  "orodja.arkada": "Аркада",

  "nast.naslov": "Настройки",
  "nast.nazaj": "Назад",
  "nast.zapri": "Затвори",
  "nast.videz": "Облик",
  "nast.jezik": "Език",
  "nast.prosojnost": "Прозрачност",
  "nast.tema": "Тема",
  "nast.temna": "Тъмна",
  "nast.svetla": "Светла",
  "nast.sistem": "Според системата",
  "nast.ozadje": "Фон",
  "nast.prizor": "Сцена",
  "nast.galaksija": "Галактика",
  "nast.zvezde": "Само звезди",
  "nast.izklop": "Изключено",
  "nast.daljna": "Далечна галактика",
  "nast.daljnaOpis": "Втора галактика на фона",
  "nast.galaksijaOpis": "Сияние, размер на звездите, скорост",
  "nast.gibanje": "Движение",
  "nast.odziv": "Реакция на мишката",
  "nast.odzivOpis": "Изгледът следва курсора",
  "nast.kazalec": "Курсор",
  "nast.kazalecMeri": "Собствен курсор",
  "nast.kazalecMeriOpis": "Искра вместо системния курсор",
  "nast.magnet": "Магнитни бутони",
  "nast.magnetOpis": "Бутоните се накланят към курсора",
  "nast.izris": "Изобразяване",
  "nast.sij": "Сияние",
  "nast.velikost": "Размер на звездите",
  "nast.kamera": "Камера",
  "nast.hitrost": "Скорост на орбитата",

  "zapis.zapri": "Затвори",
  "zapis.prejsnja": "Предишна",
  "zapis.naslednja": "Следваща",
  "zapis.odpri": "Отвори приложението",
  "aplikacija.demo": "Демо версия · данните са измислени",
  "aplikacija.zavihek": "Отвори в нов раздел",
  "aplikacija.zapri": "Затвори приложението",

  "viz.stran": "САЙТ",
  "viz.prizor": "СЦЕНА",
  "viz.prizorV": "галактика, 50 000 точки",
  "viz.izris": "ИЗОБРАЗЯВАНЕ",
  "viz.izrisV": "WebGL, собствен шейдър",
  "viz.ogrodje": "РАМКА",
  "viz.ogrodjeV": "Vite, без рамка",
  "viz.galerija": "ГАЛЕРИЯ",
  "viz.objav": "публикации",
  "viz.maskota": "Талисман на Jure Labs",
  "viz.zapri": "Затвори визитката",
  "viz.ascii": "ASCII анимация на Jure Labs",
  "viz.metaT": "Уеб приложения по поръчка",
  "viz.metaS": "Бързи. Надеждни. Ефективни.",

  "kmeni.novZavihek": "Отвори в нов раздел",
  "kmeni.kopiraj": "Копирай адреса",
  "kmeni.profil": "Профил",
  "kmeni.nastavitve": "Настройки",
  "kmeni.ponastavi": "Нулирай изгледа",
  "kmeni.kopirajBesedilo": "Копирай",
  "kmeni.kopirajPovezavo": "Копирай връзката",
  "kmeni.kopirajEposto": "Копирай имейл адреса",
  "kmeni.odpriSliko": "Отвори изображението",
  "kmeni.kopirajSliko": "Копирай адреса на изображението",
  "kmeni.jezik": "Език",
  "kmeni.kopirajStran": "Копирай връзката към страницата",
  "kmeni.celozaslonsko": "Цял екран",
  "kmeni.izhodCelozaslonsko": "Изход от цял екран",
  "arkada.naslov": "Аркада",
  "arkada.kmalu": "Очаквайте скоро",
  "arkada.opis": "Мини игрите идват. Скоро ще можеш да ги играеш точно тук.",

  "ogled.zapri": "Затвори изображението",
  "zemlja.slovenija": "Словения",

  "prof.zapri": "Затвори",
  "prof.objav": "публикации",
  "prof.sledilcev": "последователи",
  "prof.sledi": "следвани",
  "prof.bio": "✨ Ако не хвана звездите, ще дойда за теб.",
  "prof.uredi": "Редактирай профила",
  "prof.arhiv": "Архив",
  "prof.objave": "Публикации",
  "prof.shranjeno": "Запазени",
  "prof.oznaceno": "Отбелязани",
  "prof.razporeditev": "Оформление",

  "gal.razpored.tri": "Три колони",
  "gal.razpored.dve": "Две колони",
  "gal.razpored.stiri": "Четири колони",
  "gal.razpored.mozaik": "Мозайка",
  "gal.razpored.stopnice": "Стъпала",
  "gal.razpored.gost": "Гъсто (6–7)",
  "gal.razpored.trak": "Лента",
  "gal.razpored.izvirno": "Оригинални пропорции",
  "gal.razpored.izvirnoxl": "Оригинални пропорции XL",
  "gal.razpored.polno": "Цял екран",
  "gal.razpored.stolpci": "Тухли",
  "gal.razpored.prostor": "3D пространство",
  "gal.prostor.priblizaj": "Приближи",
  "gal.prostor.oddalji": "Отдалечи",
  "gal.razmik.da": "С разстояние",
  "gal.razmik.ne": "Без разстояние",
  "gal.sirina.robovi": "До краищата",
  "gal.sirina.cez": "Широко",
  "gal.sirina.sredina": "В центъра",
};
