/** Čeština - vmesnik. Besedila strani ostanejo slovenska, dokler niso prevedena. */
export default {
  "jezik.naslov": "Jazyk",
  "profil.aria": "Profil",
  "meni.aria": "Hlavní nabídka",
  "meni.arhiv": "Archiv",
  "meni.delo": "Práce",
  "meni.omeni": "O mně",
  "meni.stik": "Kontakt",
  "orodja.aria": "Nástroje",
  "orodja.iskanje": "Hledat",
  "orodja.nastavitve": "Nastavení",
  "orodja.arkada": "Herna",

  "nast.naslov": "Nastavení",
  "nast.nazaj": "Zpět",
  "nast.zapri": "Zavřít",
  "nast.videz": "Vzhled",
  "nast.jezik": "Jazyk",
  "nast.prosojnost": "Průhlednost",
  "nast.tema": "Motiv",
  "nast.temna": "Tmavý",
  "nast.svetla": "Světlý",
  "nast.sistem": "Podle systému",
  "nast.ozadje": "Pozadí",
  "nast.prizor": "Scéna",
  "nast.galaksija": "Galaxie",
  "nast.zvezde": "Jen hvězdy",
  "nast.izklop": "Vypnuto",
  "nast.daljna": "Vzdálená galaxie",
  "nast.daljnaOpis": "Druhá galaxie v pozadí",
  "nast.galaksijaOpis": "Záře, velikost hvězd, rychlost",
  "nast.gibanje": "Pohyb",
  "nast.odziv": "Reakce na myš",
  "nast.odzivOpis": "Pohled sleduje kurzor",
  "nast.kazalec": "Kurzor",
  "nast.kazalecMeri": "Vlastní kurzor",
  "nast.kazalecMeriOpis": "Jiskra místo systémového kurzoru",
  "nast.magnet": "Magnetická tlačítka",
  "nast.magnetOpis": "Tlačítka se naklánějí ke kurzoru",
  "nast.izris": "Vykreslování",
  "nast.sij": "Záře",
  "nast.velikost": "Velikost hvězd",
  "nast.kamera": "Kamera",
  "nast.hitrost": "Rychlost oběhu",

  "zapis.zapri": "Zavřít",
  "zapis.prejsnja": "Předchozí",
  "zapis.naslednja": "Další",
  "zapis.odpri": "Otevřít aplikaci",
  "aplikacija.demo": "Ukázková verze · data jsou smyšlená",
  "aplikacija.zavihek": "Otevřít v nové kartě",
  "aplikacija.zapri": "Zavřít aplikaci",

  "viz.stran": "WEB",
  "viz.prizor": "SCÉNA",
  "viz.prizorV": "galaxie, 50 000 bodů",
  "viz.izris": "VYKRESLOVÁNÍ",
  "viz.izrisV": "WebGL, vlastní shader",
  "viz.ogrodje": "FRAMEWORK",
  "viz.ogrodjeV": "Vite, bez frameworku",
  "viz.galerija": "GALERIE",
  "viz.objav": "příspěvků",
  "viz.maskota": "Maskot Jure Labs",
  "viz.zapri": "Zavřít vizitku",
  "viz.ascii": "ASCII animace Jure Labs",
  "viz.metaT": "Webové aplikace na míru",
  "viz.metaS": "Rychlé. Spolehlivé. Efektivní.",

  "kmeni.novZavihek": "Otevřít v nové kartě",
  "kmeni.kopiraj": "Kopírovat adresu",
  "kmeni.profil": "Profil",
  "kmeni.nastavitve": "Nastavení",
  "kmeni.ponastavi": "Obnovit pohled",
  "kmeni.kopirajBesedilo": "Kopírovat",
  "kmeni.kopirajPovezavo": "Kopírovat odkaz",
  "kmeni.kopirajEposto": "Kopírovat e-mailovou adresu",
  "kmeni.odpriSliko": "Otevřít obrázek",
  "kmeni.kopirajSliko": "Kopírovat adresu obrázku",
  "kmeni.jezik": "Jazyk",
  "kmeni.kopirajStran": "Kopírovat odkaz na stránku",
  "kmeni.celozaslonsko": "Celá obrazovka",
  "kmeni.izhodCelozaslonsko": "Ukončit celou obrazovku",
  "arkada.naslov": "Herna",
  "arkada.kmalu": "Již brzy",
  "arkada.opis": "Minihry jsou na cestě. Brzy si je zahraješ přímo tady.",

  "ogled.zapri": "Zavřít obrázek",
  "zemlja.slovenija": "Slovinsko",

  "prof.zapri": "Zavřít",
  "prof.objav": "příspěvků",
  "prof.sledilcev": "sledujících",
  "prof.sledi": "sleduje",
  "prof.bio": "✨ Když nechytím hvězdy, přijdu si pro tebe.",
  "prof.uredi": "Upravit profil",
  "prof.arhiv": "Archiv",
  "prof.objave": "Příspěvky",
  "prof.shranjeno": "Uložené",
  "prof.oznaceno": "Označené",
  "prof.razporeditev": "Rozvržení",

  "gal.razpored.tri": "Tři sloupce",
  "gal.razpored.dve": "Dva sloupce",
  "gal.razpored.stiri": "Čtyři sloupce",
  "gal.razpored.mozaik": "Mozaika",
  "gal.razpored.stopnice": "Schody",
  "gal.razpored.gost": "Hustě (6–7)",
  "gal.razpored.trak": "Pás",
  "gal.razpored.izvirno": "Původní poměry",
  "gal.razpored.izvirnoxl": "Původní poměry XL",
  "gal.razpored.polno": "Celá obrazovka",
  "gal.razpored.stolpci": "Cihly",
  "gal.razpored.prostor": "3D prostor",
  "gal.prostor.priblizaj": "Přiblížit",
  "gal.prostor.oddalji": "Oddálit",
  "gal.razmik.da": "S mezerou",
  "gal.razmik.ne": "Bez mezery",
  "gal.sirina.robovi": "Až k okrajům",
  "gal.sirina.cez": "Široce",
  "gal.sirina.sredina": "Uprostřed",
};
