/** Ελληνικά - vmesnik. Besedila strani ostanejo slovenska, dokler niso prevedena. */
export default {
  "jezik.naslov": "Γλώσσα",
  "profil.aria": "Προφίλ",
  "meni.aria": "Κύριο μενού",
  "meni.arhiv": "Αρχείο",
  "meni.delo": "Δουλειά",
  "meni.omeni": "Σχετικά με μένα",
  "meni.stik": "Επικοινωνία",
  "orodja.aria": "Εργαλεία",
  "orodja.iskanje": "Αναζήτηση",
  "orodja.nastavitve": "Ρυθμίσεις",

  "nast.naslov": "Ρυθμίσεις",
  "nast.nazaj": "Πίσω",
  "nast.zapri": "Κλείσιμο",
  "nast.videz": "Εμφάνιση",
  "nast.jezik": "Γλώσσα",
  "nast.prosojnost": "Διαφάνεια",
  "nast.tema": "Θέμα",
  "nast.temna": "Σκοτεινό",
  "nast.svetla": "Φωτεινό",
  "nast.sistem": "Σύστημα",
  "nast.ozadje": "Φόντο",
  "nast.prizor": "Σκηνή",
  "nast.galaksija": "Γαλαξίας",
  "nast.zvezde": "Μόνο αστέρια",
  "nast.izklop": "Ανενεργό",
  "nast.daljna": "Μακρινός γαλαξίας",
  "nast.daljnaOpis": "Ένας δεύτερος γαλαξίας στο φόντο",
  "nast.galaksijaOpis": "Λάμψη, μέγεθος αστεριών, ταχύτητα",
  "nast.gibanje": "Κίνηση",
  "nast.odziv": "Απόκριση στο ποντίκι",
  "nast.odzivOpis": "Η προβολή ακολουθεί τον κέρσορα",
  "nast.kazalec": "Κέρσορας",
  "nast.kazalecMeri": "Προσαρμοσμένος κέρσορας",
  "nast.kazalecMeriOpis": "Μια σπίθα αντί για τον κέρσορα του συστήματος",
  "nast.magnet": "Μαγνητικά κουμπιά",
  "nast.magnetOpis": "Τα κουμπιά γέρνουν προς τον κέρσορα",
  "nast.izris": "Απόδοση",
  "nast.sij": "Λάμψη",
  "nast.velikost": "Μέγεθος αστεριών",
  "nast.kamera": "Κάμερα",
  "nast.hitrost": "Ταχύτητα τροχιάς",

  "zapis.zapri": "Κλείσιμο",
  "zapis.prejsnja": "Προηγούμενη",
  "zapis.naslednja": "Επόμενη",

  "viz.stran": "ΙΣΤΟΤΟΠΟΣ",
  "viz.prizor": "ΣΚΗΝΗ",
  "viz.prizorV": "γαλαξίας, 50.000 σημεία",
  "viz.izris": "ΑΠΟΔΟΣΗ",
  "viz.izrisV": "WebGL, δικός μου shader",
  "viz.ogrodje": "FRAMEWORK",
  "viz.ogrodjeV": "Vite, χωρίς framework",
  "viz.galerija": "ΣΥΛΛΟΓΗ",
  "viz.objav": "δημοσιεύσεις",
  "viz.maskota": "Μασκότ της Jure Labs",
  "viz.zapri": "Κλείσιμο επαγγελματικής κάρτας",
  "viz.ascii": "Κινούμενο ASCII της Jure Labs",
  "viz.metaT": "Διαδικτυακές εφαρμογές κατά παραγγελία",
  "viz.metaS": "Γρήγορες. Αξιόπιστες. Αποδοτικές.",

  "kmeni.novZavihek": "Άνοιγμα σε νέα καρτέλα",
  "kmeni.kopiraj": "Αντιγραφή διεύθυνσης",
  "kmeni.profil": "Προφίλ",
  "kmeni.nastavitve": "Ρυθμίσεις",
  "kmeni.ponastavi": "Επαναφορά προβολής",

  "ogled.zapri": "Κλείσιμο εικόνας",
  "zemlja.slovenija": "Σλοβενία",

  "prof.zapri": "Κλείσιμο",
  "prof.objav": "δημοσιεύσεις",
  "prof.sledilcev": "ακόλουθοι",
  "prof.sledi": "ακολουθεί",
  "prof.bio": "✨ Αν δεν πιάσω τα αστέρια, θα έρθω για σένα.",
  "prof.uredi": "Επεξεργασία προφίλ",
  "prof.arhiv": "Αρχείο",
  "prof.objave": "Δημοσιεύσεις",
  "prof.shranjeno": "Αποθηκευμένα",
  "prof.oznaceno": "Με ετικέτα",
  "prof.razporeditev": "Διάταξη",

  "gal.razpored.tri": "Τρεις στήλες",
  "gal.razpored.dve": "Δύο στήλες",
  "gal.razpored.stiri": "Τέσσερις στήλες",
  "gal.razpored.mozaik": "Μωσαϊκό",
  "gal.razpored.stopnice": "Σκαλοπάτια",
  "gal.razpored.gost": "Πυκνό (6–7)",
  "gal.razpored.trak": "Λωρίδα",
  "gal.razpored.izvirno": "Αρχικές αναλογίες",
  "gal.razpored.izvirnoxl": "Αρχικές αναλογίες XL",
  "gal.razpored.polno": "Πλήρης οθόνη",
  "gal.razpored.stolpci": "Τούβλα",
  "gal.razmik.da": "Με κενό",
  "gal.razmik.ne": "Χωρίς κενό",
  "gal.sirina.robovi": "Ως τις άκρες",
  "gal.sirina.cez": "Φαρδύ",
  "gal.sirina.sredina": "Στο κέντρο",
};
