/** Español - vmesnik. Besedila strani ostanejo slovenska, dokler niso prevedena. */
export default {
  "jezik.naslov": "Idioma",
  "profil.aria": "Perfil",
  "meni.aria": "Menú principal",
  "meni.arhiv": "Archivo",
  "meni.delo": "Trabajo",
  "meni.omeni": "Sobre mí",
  "meni.stik": "Contacto",
  "orodja.aria": "Herramientas",
  "orodja.iskanje": "Buscar",
  "orodja.nastavitve": "Ajustes",

  "nast.naslov": "Ajustes",
  "nast.nazaj": "Atrás",
  "nast.zapri": "Cerrar",
  "nast.videz": "Apariencia",
  "nast.jezik": "Idioma",
  "nast.prosojnost": "Transparencia",
  "nast.tema": "Tema",
  "nast.temna": "Oscuro",
  "nast.svetla": "Claro",
  "nast.sistem": "Sistema",
  "nast.ozadje": "Fondo",
  "nast.prizor": "Escena",
  "nast.galaksija": "Galaxia",
  "nast.zvezde": "Solo estrellas",
  "nast.izklop": "Desactivado",
  "nast.daljna": "Galaxia lejana",
  "nast.daljnaOpis": "Una segunda galaxia al fondo",
  "nast.galaksijaOpis": "Brillo, tamaño de estrellas, velocidad",
  "nast.gibanje": "Movimiento",
  "nast.odziv": "Respuesta al ratón",
  "nast.odzivOpis": "La vista sigue al cursor",
  "nast.kazalec": "Cursor",
  "nast.kazalecMeri": "Cursor personalizado",
  "nast.kazalecMeriOpis": "Una chispa en lugar del cursor del sistema",
  "nast.magnet": "Botones magnéticos",
  "nast.magnetOpis": "Los botones se inclinan hacia el cursor",
  "nast.izris": "Renderizado",
  "nast.sij": "Brillo",
  "nast.velikost": "Tamaño de estrellas",
  "nast.kamera": "Cámara",
  "nast.hitrost": "Velocidad de órbita",

  "zapis.zapri": "Cerrar",
  "zapis.prejsnja": "Anterior",
  "zapis.naslednja": "Siguiente",
  "zapis.odpri": "Abrir la app",
  "aplikacija.demo": "Versión demo · los datos son ficticios",
  "aplikacija.zavihek": "Abrir en una pestaña nueva",
  "aplikacija.zapri": "Cerrar la app",

  "viz.stran": "SITIO",
  "viz.prizor": "ESCENA",
  "viz.prizorV": "galaxia, 50 000 puntos",
  "viz.izris": "RENDERIZADO",
  "viz.izrisV": "WebGL, shader propio",
  "viz.ogrodje": "FRAMEWORK",
  "viz.ogrodjeV": "Vite, sin framework",
  "viz.galerija": "GALERÍA",
  "viz.objav": "publicaciones",
  "viz.maskota": "Mascota de Jure Labs",
  "viz.zapri": "Cerrar tarjeta de visita",
  "viz.ascii": "Animación ASCII de Jure Labs",
  "viz.metaT": "Aplicaciones web a medida",
  "viz.metaS": "Rápidas. Fiables. Eficientes.",

  "kmeni.novZavihek": "Abrir en una pestaña nueva",
  "kmeni.kopiraj": "Copiar dirección",
  "kmeni.profil": "Perfil",
  "kmeni.nastavitve": "Ajustes",
  "kmeni.ponastavi": "Restablecer vista",
  "kmeni.kopirajBesedilo": "Copiar",
  "kmeni.kopirajPovezavo": "Copiar enlace",
  "kmeni.kopirajEposto": "Copiar dirección de correo",
  "kmeni.odpriSliko": "Abrir imagen",
  "kmeni.kopirajSliko": "Copiar dirección de la imagen",
  "kmeni.jezik": "Idioma",
  "kmeni.kopirajStran": "Copiar enlace de la página",
  "kmeni.celozaslonsko": "Pantalla completa",
  "kmeni.izhodCelozaslonsko": "Salir de pantalla completa",

  "ogled.zapri": "Cerrar imagen",
  "zemlja.slovenija": "Eslovenia",

  "prof.zapri": "Cerrar",
  "prof.objav": "publicaciones",
  "prof.sledilcev": "seguidores",
  "prof.sledi": "seguidos",
  "prof.bio": "✨ Si no atrapo las estrellas, iré a por ti.",
  "prof.uredi": "Editar perfil",
  "prof.arhiv": "Archivo",
  "prof.objave": "Publicaciones",
  "prof.shranjeno": "Guardado",
  "prof.oznaceno": "Etiquetado",
  "prof.razporeditev": "Diseño",

  "gal.razpored.tri": "Tres columnas",
  "gal.razpored.dve": "Dos columnas",
  "gal.razpored.stiri": "Cuatro columnas",
  "gal.razpored.mozaik": "Mosaico",
  "gal.razpored.stopnice": "Escalones",
  "gal.razpored.gost": "Denso (6–7)",
  "gal.razpored.trak": "Tira",
  "gal.razpored.izvirno": "Proporciones originales",
  "gal.razpored.izvirnoxl": "Proporciones originales XL",
  "gal.razpored.polno": "Pantalla completa",
  "gal.razpored.stolpci": "Ladrillo",
  "gal.razpored.prostor": "Espacio 3D",
  "gal.prostor.priblizaj": "Acercar",
  "gal.prostor.oddalji": "Alejar",
  "gal.razmik.da": "Con espacio",
  "gal.razmik.ne": "Sin espacio",
  "gal.sirina.robovi": "De borde a borde",
  "gal.sirina.cez": "Ancho",
  "gal.sirina.sredina": "Centrado",
};
