/** Suomi - vmesnik. Besedila strani ostanejo slovenska, dokler niso prevedena. */
export default {
  "jezik.naslov": "Kieli",
  "profil.aria": "Profiili",
  "meni.aria": "Päävalikko",
  "meni.arhiv": "Arkisto",
  "meni.delo": "Työt",
  "meni.omeni": "Minusta",
  "meni.stik": "Yhteystiedot",
  "orodja.aria": "Työkalut",
  "orodja.iskanje": "Haku",
  "orodja.nastavitve": "Asetukset",
  "orodja.arkada": "Pelihalli",

  "nast.naslov": "Asetukset",
  "nast.nazaj": "Takaisin",
  "nast.zapri": "Sulje",
  "nast.videz": "Ulkoasu",
  "nast.jezik": "Kieli",
  "nast.prosojnost": "Läpinäkyvyys",
  "nast.tema": "Teema",
  "nast.temna": "Tumma",
  "nast.svetla": "Vaalea",
  "nast.sistem": "Järjestelmä",
  "nast.ozadje": "Tausta",
  "nast.prizor": "Näkymä",
  "nast.galaksija": "Galaksi",
  "nast.zvezde": "Vain tähdet",
  "nast.izklop": "Pois",
  "nast.daljna": "Kaukainen galaksi",
  "nast.daljnaOpis": "Toinen galaksi taustalla",
  "nast.galaksijaOpis": "Hehku, tähtien koko, nopeus",
  "nast.gibanje": "Liike",
  "nast.odziv": "Hiiren vaste",
  "nast.odzivOpis": "Näkymä seuraa osoitinta",
  "nast.kazalec": "Osoitin",
  "nast.kazalecMeri": "Oma osoitin",
  "nast.kazalecMeriOpis": "Kipinä järjestelmän osoittimen tilalla",
  "nast.magnet": "Magneettiset painikkeet",
  "nast.magnetOpis": "Painikkeet kallistuvat osoitinta kohti",
  "nast.izris": "Renderöinti",
  "nast.sij": "Hehku",
  "nast.velikost": "Tähtien koko",
  "nast.kamera": "Kamera",
  "nast.hitrost": "Kiertonopeus",

  "zapis.zapri": "Sulje",
  "zapis.prejsnja": "Edellinen",
  "zapis.naslednja": "Seuraava",
  "zapis.odpri": "Avaa sovellus",
  "zapis.seVec": "ja muuta",
  "aplikacija.demo": "Esittelyversio · tiedot ovat keksittyjä",
  "aplikacija.zavihek": "Avaa uudessa välilehdessä",
  "aplikacija.zapri": "Sulje sovellus",

  "viz.stran": "SIVUSTO",
  "viz.prizor": "NÄKYMÄ",
  "viz.prizorV": "galaksi, 50 000 pistettä",
  "viz.izris": "RENDERÖINTI",
  "viz.izrisV": "WebGL, oma varjostin",
  "viz.ogrodje": "KEHYS",
  "viz.ogrodjeV": "Vite, ei kehystä",
  "viz.galerija": "GALLERIA",
  "viz.objav": "julkaisua",
  "viz.maskota": "Jure Labsin maskotti",
  "viz.zapri": "Sulje käyntikortti",
  "viz.ascii": "Jure Labsin ASCII-animaatio",
  "viz.metaT": "Räätälöidyt verkkosovellukset",
  "viz.metaS": "Nopeat. Luotettavat. Tehokkaat.",

  "kmeni.novZavihek": "Avaa uudessa välilehdessä",
  "kmeni.kopiraj": "Kopioi osoite",
  "kmeni.profil": "Profiili",
  "kmeni.nastavitve": "Asetukset",
  "kmeni.ponastavi": "Palauta näkymä",
  "kmeni.kopirajBesedilo": "Kopioi",
  "kmeni.kopirajPovezavo": "Kopioi linkki",
  "kmeni.kopirajEposto": "Kopioi sähköpostiosoite",
  "kmeni.odpriSliko": "Avaa kuva",
  "kmeni.kopirajSliko": "Kopioi kuvan osoite",
  "kmeni.jezik": "Kieli",
  "kmeni.kopirajStran": "Kopioi sivun linkki",
  "kmeni.celozaslonsko": "Koko näyttö",
  "kmeni.izhodCelozaslonsko": "Poistu koko näytöstä",
  "arkada.naslov": "Pelihalli",
  "arkada.kmalu": "Tulossa pian",
  "arkada.opis": "Minipelit ovat tulossa. Pian voit pelata niitä täällä.",

  "ogled.zapri": "Sulje kuva",
  "zemlja.slovenija": "Slovenia",

  "prof.zapri": "Sulje",
  "prof.objav": "julkaisua",
  "prof.sledilcev": "seuraajaa",
  "prof.sledi": "seurattua",
  "prof.uredi": "Muokkaa profiilia",
  "prof.arhiv": "Arkisto",
  "prof.objave": "Julkaisut",
  "prof.shranjeno": "Tallennetut",
  "prof.oznaceno": "Merkityt",
  "prof.razporeditev": "Asettelu",

  "gal.razpored.tri": "Kolme saraketta",
  "gal.razpored.dve": "Kaksi saraketta",
  "gal.razpored.stiri": "Neljä saraketta",
  "gal.razpored.mozaik": "Mosaiikki",
  "gal.razpored.stopnice": "Porras",
  "gal.razpored.gost": "Tiheä (6–7)",
  "gal.razpored.trak": "Nauha",
  "gal.razpored.izvirno": "Alkuperäiset mittasuhteet",
  "gal.razpored.izvirnoxl": "Alkuperäiset mittasuhteet XL",
  "gal.razpored.polno": "Koko näyttö",
  "gal.razpored.stolpci": "Tiili",
  "gal.razpored.prostor": "3D-tila",
  "gal.prostor.priblizaj": "Lähennä",
  "gal.prostor.oddalji": "Loitonna",
  "gal.razmik.da": "Välillä",
  "gal.razmik.ne": "Ilman väliä",
  "gal.sirina.robovi": "Reunasta reunaan",
  "gal.sirina.cez": "Leveä",
  "gal.sirina.sredina": "Keskitetty",
};
