/** Français - vmesnik. Besedila strani ostanejo slovenska, dokler niso prevedena. */
export default {
  "jezik.naslov": "Langue",
  "profil.aria": "Profil",
  "meni.aria": "Menu principal",
  "meni.arhiv": "Archives",
  "meni.delo": "Travail",
  "meni.omeni": "À propos",
  "meni.stik": "Contact",
  "orodja.aria": "Outils",
  "orodja.iskanje": "Recherche",
  "orodja.nastavitve": "Réglages",

  "nast.naslov": "Réglages",
  "nast.nazaj": "Retour",
  "nast.zapri": "Fermer",
  "nast.videz": "Apparence",
  "nast.jezik": "Langue",
  "nast.prosojnost": "Transparence",
  "nast.tema": "Thème",
  "nast.temna": "Sombre",
  "nast.svetla": "Clair",
  "nast.sistem": "Système",
  "nast.ozadje": "Arrière-plan",
  "nast.prizor": "Scène",
  "nast.galaksija": "Galaxie",
  "nast.zvezde": "Étoiles seules",
  "nast.izklop": "Désactivé",
  "nast.daljna": "Galaxie lointaine",
  "nast.daljnaOpis": "Une seconde galaxie en arrière-plan",
  "nast.galaksijaOpis": "Lueur, taille des étoiles, vitesse",
  "nast.gibanje": "Mouvement",
  "nast.odziv": "Réaction à la souris",
  "nast.odzivOpis": "La vue suit le curseur",
  "nast.kazalec": "Curseur",
  "nast.kazalecMeri": "Curseur personnalisé",
  "nast.kazalecMeriOpis": "Une étincelle à la place du curseur système",
  "nast.magnet": "Boutons magnétiques",
  "nast.magnetOpis": "Les boutons s'inclinent vers le curseur",
  "nast.izris": "Rendu",
  "nast.sij": "Lueur",
  "nast.velikost": "Taille des étoiles",
  "nast.kamera": "Caméra",
  "nast.hitrost": "Vitesse d'orbite",

  "zapis.zapri": "Fermer",
  "zapis.prejsnja": "Précédente",
  "zapis.naslednja": "Suivante",

  "viz.stran": "SITE",
  "viz.prizor": "SCÈNE",
  "viz.prizorV": "galaxie, 50 000 points",
  "viz.izris": "RENDU",
  "viz.izrisV": "WebGL, shader maison",
  "viz.ogrodje": "FRAMEWORK",
  "viz.ogrodjeV": "Vite, sans framework",
  "viz.galerija": "GALERIE",
  "viz.objav": "publications",
  "viz.maskota": "Mascotte Jure Labs",
  "viz.zapri": "Fermer la carte de visite",
  "viz.ascii": "Animation ASCII Jure Labs",
  "viz.metaT": "Applications web sur mesure",
  "viz.metaS": "Rapides. Fiables. Efficaces.",

  "kmeni.novZavihek": "Ouvrir dans un nouvel onglet",
  "kmeni.kopiraj": "Copier l'adresse",
  "kmeni.profil": "Profil",
  "kmeni.nastavitve": "Réglages",
  "kmeni.ponastavi": "Réinitialiser la vue",

  "ogled.zapri": "Fermer l'image",
  "zemlja.slovenija": "Slovénie",

  "prof.zapri": "Fermer",
  "prof.objav": "publications",
  "prof.sledilcev": "abonnés",
  "prof.sledi": "abonnements",
  "prof.bio": "✨ Si je n'attrape pas les étoiles, je viendrai te chercher.",
  "prof.uredi": "Modifier le profil",
  "prof.arhiv": "Archives",
  "prof.objave": "Publications",
  "prof.shranjeno": "Enregistrés",
  "prof.oznaceno": "Identifié",
  "prof.razporeditev": "Disposition",

  "gal.razpored.tri": "Trois colonnes",
  "gal.razpored.dve": "Deux colonnes",
  "gal.razpored.stiri": "Quatre colonnes",
  "gal.razpored.mozaik": "Mosaïque",
  "gal.razpored.stopnice": "Escalier",
  "gal.razpored.gost": "Dense (6–7)",
  "gal.razpored.trak": "Bande",
  "gal.razpored.izvirno": "Proportions d'origine",
  "gal.razpored.izvirnoxl": "Proportions d'origine XL",
  "gal.razpored.polno": "Plein écran",
  "gal.razpored.stolpci": "Briques",
  "gal.razpored.prostor": "Espace 3D",
  "gal.prostor.priblizaj": "Zoom avant",
  "gal.prostor.oddalji": "Zoom arrière",
  "gal.razmik.da": "Avec espacement",
  "gal.razmik.ne": "Sans espacement",
  "gal.sirina.robovi": "Bord à bord",
  "gal.sirina.cez": "Large",
  "gal.sirina.sredina": "Centré",
};
