/** עברית - vmesnik. Besedila strani ostanejo slovenska, dokler niso prevedena. */
export default {
  "jezik.naslov": "שפה",
  "profil.aria": "פרופיל",
  "meni.aria": "תפריט ראשי",
  "meni.arhiv": "ארכיון",
  "meni.delo": "עבודות",
  "meni.omeni": "עליי",
  "meni.stik": "צור קשר",
  "orodja.aria": "כלים",
  "orodja.iskanje": "חיפוש",
  "orodja.nastavitve": "הגדרות",
  "orodja.arkada": "ארקייד",

  "nast.naslov": "הגדרות",
  "nast.nazaj": "חזרה",
  "nast.zapri": "סגירה",
  "nast.videz": "מראה",
  "nast.jezik": "שפה",
  "nast.prosojnost": "שקיפות",
  "nast.tema": "ערכת נושא",
  "nast.temna": "כהה",
  "nast.svetla": "בהירה",
  "nast.sistem": "לפי המערכת",
  "nast.ozadje": "רקע",
  "nast.prizor": "סצנה",
  "nast.galaksija": "גלקסיה",
  "nast.zvezde": "כוכבים בלבד",
  "nast.izklop": "כבוי",
  "nast.daljna": "גלקסיה רחוקה",
  "nast.daljnaOpis": "גלקסיה שנייה ברקע",
  "nast.galaksijaOpis": "זוהר, גודל כוכבים, מהירות",
  "nast.gibanje": "תנועה",
  "nast.odziv": "תגובה לעכבר",
  "nast.odzivOpis": "התצוגה עוקבת אחרי הסמן",
  "nast.kazalec": "סמן",
  "nast.kazalecMeri": "סמן מותאם",
  "nast.kazalecMeriOpis": "ניצוץ במקום סמן המערכת",
  "nast.magnet": "כפתורים מגנטיים",
  "nast.magnetOpis": "הכפתורים נוטים לעבר הסמן",
  "nast.izris": "רינדור",
  "nast.sij": "זוהר",
  "nast.velikost": "גודל כוכבים",
  "nast.kamera": "מצלמה",
  "nast.hitrost": "מהירות מסלול",

  "zapis.zapri": "סגירה",
  "zapis.prejsnja": "הקודמת",
  "zapis.naslednja": "הבאה",
  "zapis.odpri": "פתיחת האפליקציה",
  "zapis.seVec": "ועוד",
  "aplikacija.demo": "גרסת הדגמה · הנתונים בדויים",
  "aplikacija.zavihek": "פתיחה בכרטיסייה חדשה",
  "aplikacija.zapri": "סגירת האפליקציה",

  "viz.stran": "אתר",
  "viz.prizor": "סצנה",
  "viz.prizorV": "גלקסיה, 50,000 נקודות",
  "viz.izris": "רינדור",
  "viz.izrisV": "WebGL, שיידר משלי",
  "viz.ogrodje": "פריימוורק",
  "viz.ogrodjeV": "Vite, בלי פריימוורק",
  "viz.galerija": "גלריה",
  "viz.objav": "פוסטים",
  "viz.maskota": "הקמע של Jure Labs",
  "viz.zapri": "סגירת כרטיס הביקור",
  "viz.ascii": "אנימציית ASCII של Jure Labs",
  "viz.metaT": "אפליקציות ווב בהתאמה אישית",
  "viz.metaS": "מהירות. אמינות. יעילות.",

  "kmeni.novZavihek": "פתיחה בכרטיסייה חדשה",
  "kmeni.kopiraj": "העתקת כתובת",
  "kmeni.profil": "פרופיל",
  "kmeni.nastavitve": "הגדרות",
  "kmeni.ponastavi": "איפוס התצוגה",
  "kmeni.kopirajBesedilo": "העתק",
  "kmeni.kopirajPovezavo": "העתק קישור",
  "kmeni.kopirajEposto": "העתק כתובת דוא״ל",
  "kmeni.odpriSliko": "פתח תמונה",
  "kmeni.kopirajSliko": "העתק כתובת תמונה",
  "kmeni.jezik": "שפה",
  "kmeni.kopirajStran": "העתק קישור לדף",
  "kmeni.celozaslonsko": "מסך מלא",
  "kmeni.izhodCelozaslonsko": "צא ממסך מלא",
  "arkada.naslov": "ארקייד",
  "arkada.kmalu": "בקרוב",
  "arkada.opis": "משחקי המיני בדרך. בקרוב תוכל לשחק בהם כאן.",

  "ogled.zapri": "סגירת התמונה",
  "zemlja.slovenija": "סלובניה",

  "prof.zapri": "סגירה",
  "prof.objav": "פוסטים",
  "prof.sledilcev": "עוקבים",
  "prof.sledi": "נעקבים",
  "prof.bio": "✨ אם לא אתפוס את הכוכבים, אבוא אלייך.",
  "prof.uredi": "עריכת פרופיל",
  "prof.arhiv": "ארכיון",
  "prof.objave": "פוסטים",
  "prof.shranjeno": "שמורים",
  "prof.oznaceno": "תיוגים",
  "prof.razporeditev": "פריסה",

  "gal.razpored.tri": "שלוש עמודות",
  "gal.razpored.dve": "שתי עמודות",
  "gal.razpored.stiri": "ארבע עמודות",
  "gal.razpored.mozaik": "פסיפס",
  "gal.razpored.stopnice": "מדרגות",
  "gal.razpored.gost": "צפוף (6–7)",
  "gal.razpored.trak": "רצועה",
  "gal.razpored.izvirno": "יחס מקורי",
  "gal.razpored.izvirnoxl": "יחס מקורי XL",
  "gal.razpored.polno": "מסך מלא",
  "gal.razpored.stolpci": "לבנים",
  "gal.razpored.prostor": "מרחב תלת־ממדי",
  "gal.prostor.priblizaj": "הגדלה",
  "gal.prostor.oddalji": "הקטנה",
  "gal.razmik.da": "עם רווח",
  "gal.razmik.ne": "בלי רווח",
  "gal.sirina.robovi": "עד הקצוות",
  "gal.sirina.cez": "רחב",
  "gal.sirina.sredina": "במרכז",
};
