/** हिन्दी - vmesnik. Besedila strani ostanejo slovenska, dokler niso prevedena. */
export default {
  "jezik.naslov": "भाषा",
  "profil.aria": "प्रोफ़ाइल",
  "meni.aria": "मुख्य मेन्यू",
  "meni.arhiv": "संग्रह",
  "meni.delo": "काम",
  "meni.omeni": "मेरे बारे में",
  "meni.stik": "संपर्क",
  "orodja.aria": "टूल",
  "orodja.iskanje": "खोज",
  "orodja.nastavitve": "सेटिंग्स",

  "nast.naslov": "सेटिंग्स",
  "nast.nazaj": "वापस",
  "nast.zapri": "बंद करें",
  "nast.videz": "रूप",
  "nast.jezik": "भाषा",
  "nast.prosojnost": "पारदर्शिता",
  "nast.tema": "थीम",
  "nast.temna": "गहरी",
  "nast.svetla": "हल्की",
  "nast.sistem": "सिस्टम",
  "nast.ozadje": "पृष्ठभूमि",
  "nast.prizor": "दृश्य",
  "nast.galaksija": "आकाशगंगा",
  "nast.zvezde": "केवल तारे",
  "nast.izklop": "बंद",
  "nast.daljna": "दूर की आकाशगंगा",
  "nast.daljnaOpis": "पृष्ठभूमि में दूसरी आकाशगंगा",
  "nast.galaksijaOpis": "चमक, तारों का आकार, गति",
  "nast.gibanje": "गति",
  "nast.odziv": "माउस पर प्रतिक्रिया",
  "nast.odzivOpis": "दृश्य कर्सर का पीछा करता है",
  "nast.kazalec": "कर्सर",
  "nast.kazalecMeri": "अपना कर्सर",
  "nast.kazalecMeriOpis": "सिस्टम कर्सर की जगह एक चिंगारी",
  "nast.magnet": "चुंबकीय बटन",
  "nast.magnetOpis": "बटन कर्सर की ओर झुकते हैं",
  "nast.izris": "रेंडरिंग",
  "nast.sij": "चमक",
  "nast.velikost": "तारों का आकार",
  "nast.kamera": "कैमरा",
  "nast.hitrost": "कक्षा की गति",

  "zapis.zapri": "बंद करें",
  "zapis.prejsnja": "पिछली",
  "zapis.naslednja": "अगली",

  "viz.stran": "साइट",
  "viz.prizor": "दृश्य",
  "viz.prizorV": "आकाशगंगा, 50,000 बिंदु",
  "viz.izris": "रेंडरिंग",
  "viz.izrisV": "WebGL, अपना शेडर",
  "viz.ogrodje": "फ़्रेमवर्क",
  "viz.ogrodjeV": "Vite, बिना फ़्रेमवर्क",
  "viz.galerija": "गैलरी",
  "viz.objav": "पोस्ट",
  "viz.maskota": "Jure Labs शुभंकर",
  "viz.zapri": "विज़िटिंग कार्ड बंद करें",
  "viz.ascii": "Jure Labs ASCII एनिमेशन",
  "viz.metaT": "कस्टम वेब ऐप्स",
  "viz.metaS": "तेज़। भरोसेमंद। कुशल।",

  "kmeni.novZavihek": "नए टैब में खोलें",
  "kmeni.kopiraj": "पता कॉपी करें",
  "kmeni.profil": "प्रोफ़ाइल",
  "kmeni.nastavitve": "सेटिंग्स",
  "kmeni.ponastavi": "दृश्य रीसेट करें",

  "ogled.zapri": "चित्र बंद करें",
  "zemlja.slovenija": "स्लोवेनिया",

  "prof.zapri": "बंद करें",
  "prof.objav": "पोस्ट",
  "prof.sledilcev": "फ़ॉलोअर्स",
  "prof.sledi": "फ़ॉलोइंग",
  "prof.bio": "✨ अगर तारे न पकड़ पाया, तो तुम्हारे लिए आऊँगा।",
  "prof.uredi": "प्रोफ़ाइल संपादित करें",
  "prof.arhiv": "संग्रह",
  "prof.objave": "पोस्ट",
  "prof.shranjeno": "सहेजे गए",
  "prof.oznaceno": "टैग किए गए",
  "prof.razporeditev": "लेआउट",

  "gal.razpored.tri": "तीन कॉलम",
  "gal.razpored.dve": "दो कॉलम",
  "gal.razpored.stiri": "चार कॉलम",
  "gal.razpored.mozaik": "मोज़ेक",
  "gal.razpored.stopnice": "सीढ़ियाँ",
  "gal.razpored.gost": "घना (6–7)",
  "gal.razpored.trak": "पट्टी",
  "gal.razpored.izvirno": "मूल अनुपात",
  "gal.razpored.izvirnoxl": "मूल अनुपात XL",
  "gal.razpored.polno": "पूर्ण स्क्रीन",
  "gal.razpored.stolpci": "ईंटें",
  "gal.razmik.da": "अंतराल के साथ",
  "gal.razmik.ne": "बिना अंतराल",
  "gal.sirina.robovi": "किनारे तक",
  "gal.sirina.cez": "चौड़ा",
  "gal.sirina.sredina": "बीच में",
};
