/** Hrvatski - vmesnik. Besedila strani ostanejo slovenska, dokler niso prevedena. */
export default {
  "jezik.naslov": "Jezik",
  "profil.aria": "Profil",
  "meni.aria": "Glavni izbornik",
  "meni.arhiv": "Arhiva",
  "meni.delo": "Rad",
  "meni.omeni": "O meni",
  "meni.stik": "Kontakt",
  "orodja.aria": "Alati",
  "orodja.iskanje": "Pretraživanje",
  "orodja.nastavitve": "Postavke",
  "orodja.arkada": "Arkada",

  "nast.naslov": "Postavke",
  "nast.nazaj": "Natrag",
  "nast.zapri": "Zatvori",
  "nast.videz": "Izgled",
  "nast.jezik": "Jezik",
  "nast.prosojnost": "Prozirnost",
  "nast.tema": "Tema",
  "nast.temna": "Tamna",
  "nast.svetla": "Svijetla",
  "nast.sistem": "Prema sustavu",
  "nast.ozadje": "Pozadina",
  "nast.prizor": "Prizor",
  "nast.galaksija": "Galaksija",
  "nast.zvezde": "Samo zvijezde",
  "nast.izklop": "Isključeno",
  "nast.daljna": "Udaljena galaksija",
  "nast.daljnaOpis": "Druga galaksija u pozadini",
  "nast.galaksijaOpis": "Sjaj, veličina zvijezda, brzina",
  "nast.gibanje": "Kretanje",
  "nast.odziv": "Odziv na miš",
  "nast.odzivOpis": "Pogled prati pokazivač",
  "nast.kazalec": "Pokazivač",
  "nast.kazalecMeri": "Vlastiti pokazivač",
  "nast.kazalecMeriOpis": "Iskra umjesto sistemskog pokazivača",
  "nast.magnet": "Magnetski gumbi",
  "nast.magnetOpis": "Gumbi se naginju prema pokazivaču",
  "nast.izris": "Iscrtavanje",
  "nast.sij": "Sjaj",
  "nast.velikost": "Veličina zvijezda",
  "nast.kamera": "Kamera",
  "nast.hitrost": "Brzina orbite",

  "zapis.zapri": "Zatvori",
  "zapis.prejsnja": "Prethodna",
  "zapis.naslednja": "Sljedeća",
  "zapis.odpri": "Otvori aplikaciju",
  "zapis.seVec": "i više",
  "aplikacija.demo": "Demo verzija · podaci su izmišljeni",
  "aplikacija.zavihek": "Otvori u novoj kartici",
  "aplikacija.zapri": "Zatvori aplikaciju",

  "viz.stran": "STRANICA",
  "viz.prizor": "PRIZOR",
  "viz.prizorV": "galaksija, 50 000 točaka",
  "viz.izris": "ISCRTAVANJE",
  "viz.izrisV": "WebGL, vlastiti shader",
  "viz.ogrodje": "OKVIR",
  "viz.ogrodjeV": "Vite, bez okvira",
  "viz.galerija": "GALERIJA",
  "viz.objav": "objava",
  "viz.maskota": "Maskota Jure Labs",
  "viz.zapri": "Zatvori posjetnicu",
  "viz.ascii": "ASCII animacija Jure Labs",
  "viz.metaT": "Web aplikacije po mjeri",
  "viz.metaS": "Brze. Pouzdane. Učinkovite.",

  "kmeni.novZavihek": "Otvori u novoj kartici",
  "kmeni.kopiraj": "Kopiraj adresu",
  "kmeni.profil": "Profil",
  "kmeni.nastavitve": "Postavke",
  "kmeni.ponastavi": "Vrati pogled",
  "kmeni.kopirajBesedilo": "Kopiraj",
  "kmeni.kopirajPovezavo": "Kopiraj poveznicu",
  "kmeni.kopirajEposto": "Kopiraj adresu e-pošte",
  "kmeni.odpriSliko": "Otvori sliku",
  "kmeni.kopirajSliko": "Kopiraj adresu slike",
  "kmeni.jezik": "Jezik",
  "kmeni.kopirajStran": "Kopiraj poveznicu stranice",
  "kmeni.celozaslonsko": "Cijeli zaslon",
  "kmeni.izhodCelozaslonsko": "Izađi iz cijelog zaslona",
  "arkada.naslov": "Arkada",
  "arkada.kmalu": "Uskoro",
  "arkada.opis": "Mini igre su u izradi. Uskoro ćeš ih moći igrati baš ovdje.",

  "ogled.zapri": "Zatvori sliku",
  "zemlja.slovenija": "Slovenija",

  "prof.zapri": "Zatvori",
  "prof.objav": "objava",
  "prof.sledilcev": "pratitelja",
  "prof.sledi": "prati",
  "prof.uredi": "Uredi profil",
  "prof.arhiv": "Arhiva",
  "prof.objave": "Objave",
  "prof.shranjeno": "Spremljeno",
  "prof.oznaceno": "Označeno",
  "prof.razporeditev": "Raspored",

  "gal.razpored.tri": "Tri stupca",
  "gal.razpored.dve": "Dva stupca",
  "gal.razpored.stiri": "Četiri stupca",
  "gal.razpored.mozaik": "Mozaik",
  "gal.razpored.stopnice": "Stepenice",
  "gal.razpored.gost": "Gusto (6–7)",
  "gal.razpored.trak": "Traka",
  "gal.razpored.izvirno": "Izvorni omjeri",
  "gal.razpored.izvirnoxl": "Izvorni omjeri XL",
  "gal.razpored.polno": "Cijeli zaslon",
  "gal.razpored.stolpci": "Cigle",
  "gal.razpored.prostor": "3D prostor",
  "gal.prostor.priblizaj": "Približi",
  "gal.prostor.oddalji": "Udalji",
  "gal.razmik.da": "S razmakom",
  "gal.razmik.ne": "Bez razmaka",
  "gal.sirina.robovi": "Do rubova",
  "gal.sirina.cez": "Široko",
  "gal.sirina.sredina": "U sredini",
};
