/** Magyar - vmesnik. Besedila strani ostanejo slovenska, dokler niso prevedena. */
export default {
  "jezik.naslov": "Nyelv",
  "profil.aria": "Profil",
  "meni.aria": "Főmenü",
  "meni.arhiv": "Archívum",
  "meni.delo": "Munka",
  "meni.omeni": "Rólam",
  "meni.stik": "Kapcsolat",
  "orodja.aria": "Eszközök",
  "orodja.iskanje": "Keresés",
  "orodja.nastavitve": "Beállítások",
  "orodja.arkada": "Játékterem",

  "nast.naslov": "Beállítások",
  "nast.nazaj": "Vissza",
  "nast.zapri": "Bezárás",
  "nast.videz": "Megjelenés",
  "nast.jezik": "Nyelv",
  "nast.prosojnost": "Átlátszóság",
  "nast.tema": "Téma",
  "nast.temna": "Sötét",
  "nast.svetla": "Világos",
  "nast.sistem": "Rendszer",
  "nast.ozadje": "Háttér",
  "nast.prizor": "Jelenet",
  "nast.galaksija": "Galaxis",
  "nast.zvezde": "Csak csillagok",
  "nast.izklop": "Ki",
  "nast.daljna": "Távoli galaxis",
  "nast.daljnaOpis": "Egy második galaxis a háttérben",
  "nast.galaksijaOpis": "Ragyogás, csillagméret, sebesség",
  "nast.gibanje": "Mozgás",
  "nast.odziv": "Egérreakció",
  "nast.odzivOpis": "A nézet követi a kurzort",
  "nast.kazalec": "Kurzor",
  "nast.kazalecMeri": "Egyedi kurzor",
  "nast.kazalecMeriOpis": "Szikra a rendszerkurzor helyett",
  "nast.magnet": "Mágneses gombok",
  "nast.magnetOpis": "A gombok a kurzor felé dőlnek",
  "nast.izris": "Renderelés",
  "nast.sij": "Ragyogás",
  "nast.velikost": "Csillagméret",
  "nast.kamera": "Kamera",
  "nast.hitrost": "Keringési sebesség",

  "zapis.zapri": "Bezárás",
  "zapis.prejsnja": "Előző",
  "zapis.naslednja": "Következő",
  "zapis.odpri": "Alkalmazás megnyitása",
  "zapis.seVec": "és még több",
  "aplikacija.demo": "Bemutató verzió · az adatok kitaláltak",
  "aplikacija.zavihek": "Megnyitás új lapon",
  "aplikacija.zapri": "Alkalmazás bezárása",

  "viz.stran": "OLDAL",
  "viz.prizor": "JELENET",
  "viz.prizorV": "galaxis, 50 000 pont",
  "viz.izris": "RENDERELÉS",
  "viz.izrisV": "WebGL, saját shader",
  "viz.ogrodje": "KERETRENDSZER",
  "viz.ogrodjeV": "Vite, keretrendszer nélkül",
  "viz.galerija": "GALÉRIA",
  "viz.objav": "bejegyzés",
  "viz.maskota": "Jure Labs kabala",
  "viz.zapri": "Névjegykártya bezárása",
  "viz.ascii": "Jure Labs ASCII-animáció",
  "viz.metaT": "Egyedi webalkalmazások",
  "viz.metaS": "Gyors. Megbízható. Hatékony.",

  "kmeni.novZavihek": "Megnyitás új lapon",
  "kmeni.kopiraj": "Cím másolása",
  "kmeni.profil": "Profil",
  "kmeni.nastavitve": "Beállítások",
  "kmeni.ponastavi": "Nézet visszaállítása",
  "kmeni.kopirajBesedilo": "Másolás",
  "kmeni.kopirajPovezavo": "Hivatkozás másolása",
  "kmeni.kopirajEposto": "E-mail-cím másolása",
  "kmeni.odpriSliko": "Kép megnyitása",
  "kmeni.kopirajSliko": "Képcím másolása",
  "kmeni.jezik": "Nyelv",
  "kmeni.kopirajStran": "Oldal hivatkozásának másolása",
  "kmeni.celozaslonsko": "Teljes képernyő",
  "kmeni.izhodCelozaslonsko": "Kilépés a teljes képernyőből",
  "arkada.naslov": "Játékterem",
  "arkada.kmalu": "Hamarosan",
  "arkada.opis": "A minijátékok úton vannak. Hamarosan itt játszhatsz velük.",

  "ogled.zapri": "Kép bezárása",
  "zemlja.slovenija": "Szlovénia",

  "prof.zapri": "Bezárás",
  "prof.objav": "bejegyzés",
  "prof.sledilcev": "követő",
  "prof.sledi": "követett",
  "prof.bio": "✨ Ha nem kapom el a csillagokat, érted jövök.",
  "prof.uredi": "Profil szerkesztése",
  "prof.arhiv": "Archívum",
  "prof.objave": "Bejegyzések",
  "prof.shranjeno": "Mentett",
  "prof.oznaceno": "Megjelölt",
  "prof.razporeditev": "Elrendezés",

  "gal.razpored.tri": "Három oszlop",
  "gal.razpored.dve": "Két oszlop",
  "gal.razpored.stiri": "Négy oszlop",
  "gal.razpored.mozaik": "Mozaik",
  "gal.razpored.stopnice": "Lépcső",
  "gal.razpored.gost": "Sűrű (6–7)",
  "gal.razpored.trak": "Sáv",
  "gal.razpored.izvirno": "Eredeti arányok",
  "gal.razpored.izvirnoxl": "Eredeti arányok XL",
  "gal.razpored.polno": "Teljes képernyő",
  "gal.razpored.stolpci": "Tégla",
  "gal.razpored.prostor": "3D tér",
  "gal.prostor.priblizaj": "Nagyítás",
  "gal.prostor.oddalji": "Kicsinyítés",
  "gal.razmik.da": "Térközzel",
  "gal.razmik.ne": "Térköz nélkül",
  "gal.sirina.robovi": "Szélétől széléig",
  "gal.sirina.cez": "Széles",
  "gal.sirina.sredina": "Középen",
};
