/** Italiano - vmesnik. Besedila strani ostanejo slovenska, dokler niso prevedena. */
export default {
  "jezik.naslov": "Lingua",
  "profil.aria": "Profilo",
  "meni.aria": "Menu principale",
  "meni.arhiv": "Archivio",
  "meni.delo": "Lavoro",
  "meni.omeni": "Chi sono",
  "meni.stik": "Contatti",
  "orodja.aria": "Strumenti",
  "orodja.iskanje": "Cerca",
  "orodja.nastavitve": "Impostazioni",
  "orodja.arkada": "Arcade",

  "nast.naslov": "Impostazioni",
  "nast.nazaj": "Indietro",
  "nast.zapri": "Chiudi",
  "nast.videz": "Aspetto",
  "nast.jezik": "Lingua",
  "nast.prosojnost": "Trasparenza",
  "nast.tema": "Tema",
  "nast.temna": "Scuro",
  "nast.svetla": "Chiaro",
  "nast.sistem": "Sistema",
  "nast.ozadje": "Sfondo",
  "nast.prizor": "Scena",
  "nast.galaksija": "Galassia",
  "nast.zvezde": "Solo stelle",
  "nast.izklop": "Spento",
  "nast.daljna": "Galassia lontana",
  "nast.daljnaOpis": "Una seconda galassia sullo sfondo",
  "nast.galaksijaOpis": "Bagliore, dimensione delle stelle, velocità",
  "nast.gibanje": "Movimento",
  "nast.odziv": "Risposta al mouse",
  "nast.odzivOpis": "La vista segue il cursore",
  "nast.kazalec": "Cursore",
  "nast.kazalecMeri": "Cursore personalizzato",
  "nast.kazalecMeriOpis": "Una scintilla al posto del cursore di sistema",
  "nast.magnet": "Pulsanti magnetici",
  "nast.magnetOpis": "I pulsanti si inclinano verso il cursore",
  "nast.izris": "Resa",
  "nast.sij": "Bagliore",
  "nast.velikost": "Dimensione stelle",
  "nast.kamera": "Fotocamera",
  "nast.hitrost": "Velocità orbita",

  "zapis.zapri": "Chiudi",
  "zapis.prejsnja": "Precedente",
  "zapis.naslednja": "Successiva",
  "zapis.odpri": "Apri l'app",
  "aplikacija.demo": "Versione demo · i dati sono inventati",
  "aplikacija.zavihek": "Apri in una nuova scheda",
  "aplikacija.zapri": "Chiudi l'app",

  "viz.stran": "SITO",
  "viz.prizor": "SCENA",
  "viz.prizorV": "galassia, 50.000 punti",
  "viz.izris": "RENDERING",
  "viz.izrisV": "WebGL, shader personalizzato",
  "viz.ogrodje": "FRAMEWORK",
  "viz.ogrodjeV": "Vite, senza framework",
  "viz.galerija": "GALLERIA",
  "viz.objav": "post",
  "viz.maskota": "Mascotte di Jure Labs",
  "viz.zapri": "Chiudi biglietto da visita",
  "viz.ascii": "Animazione ASCII di Jure Labs",
  "viz.metaT": "Applicazioni web su misura",
  "viz.metaS": "Veloci. Affidabili. Efficienti.",

  "kmeni.novZavihek": "Apri in una nuova scheda",
  "kmeni.kopiraj": "Copia indirizzo",
  "kmeni.profil": "Profilo",
  "kmeni.nastavitve": "Impostazioni",
  "kmeni.ponastavi": "Ripristina vista",
  "kmeni.kopirajBesedilo": "Copia",
  "kmeni.kopirajPovezavo": "Copia link",
  "kmeni.kopirajEposto": "Copia indirizzo email",
  "kmeni.odpriSliko": "Apri immagine",
  "kmeni.kopirajSliko": "Copia indirizzo immagine",
  "kmeni.jezik": "Lingua",
  "kmeni.kopirajStran": "Copia link della pagina",
  "kmeni.celozaslonsko": "Schermo intero",
  "kmeni.izhodCelozaslonsko": "Esci da schermo intero",
  "arkada.naslov": "Arcade",
  "arkada.kmalu": "In arrivo",
  "arkada.opis": "I minigiochi sono in arrivo. Presto potrai giocarci proprio qui.",

  "ogled.zapri": "Chiudi immagine",
  "zemlja.slovenija": "Slovenia",

  "prof.zapri": "Chiudi",
  "prof.objav": "post",
  "prof.sledilcev": "follower",
  "prof.sledi": "seguiti",
  "prof.bio": "✨ Se non catturo le stelle, vengo a prendere te.",
  "prof.uredi": "Modifica profilo",
  "prof.arhiv": "Archivio",
  "prof.objave": "Post",
  "prof.shranjeno": "Salvati",
  "prof.oznaceno": "Taggati",
  "prof.razporeditev": "Layout",

  "gal.razpored.tri": "Tre colonne",
  "gal.razpored.dve": "Due colonne",
  "gal.razpored.stiri": "Quattro colonne",
  "gal.razpored.mozaik": "Mosaico",
  "gal.razpored.stopnice": "Gradini",
  "gal.razpored.gost": "Fitto (6–7)",
  "gal.razpored.trak": "Striscia",
  "gal.razpored.izvirno": "Proporzioni originali",
  "gal.razpored.izvirnoxl": "Proporzioni originali XL",
  "gal.razpored.polno": "Schermo intero",
  "gal.razpored.stolpci": "Mattoni",
  "gal.razpored.prostor": "Spazio 3D",
  "gal.prostor.priblizaj": "Ingrandisci",
  "gal.prostor.oddalji": "Riduci",
  "gal.razmik.da": "Con spaziatura",
  "gal.razmik.ne": "Senza spaziatura",
  "gal.sirina.robovi": "Fino ai bordi",
  "gal.sirina.cez": "Largo",
  "gal.sirina.sredina": "Centrato",
};
