/** 日本語 - vmesnik. Besedila strani ostanejo slovenska, dokler niso prevedena. */
export default {
  "jezik.naslov": "言語",
  "profil.aria": "プロフィール",
  "meni.aria": "メインメニュー",
  "meni.arhiv": "アーカイブ",
  "meni.delo": "仕事",
  "meni.omeni": "自己紹介",
  "meni.stik": "連絡先",
  "orodja.aria": "ツール",
  "orodja.iskanje": "検索",
  "orodja.nastavitve": "設定",

  "nast.naslov": "設定",
  "nast.nazaj": "戻る",
  "nast.zapri": "閉じる",
  "nast.videz": "外観",
  "nast.jezik": "言語",
  "nast.prosojnost": "透明度",
  "nast.tema": "テーマ",
  "nast.temna": "ダーク",
  "nast.svetla": "ライト",
  "nast.sistem": "システム",
  "nast.ozadje": "背景",
  "nast.prizor": "シーン",
  "nast.galaksija": "銀河",
  "nast.zvezde": "星のみ",
  "nast.izklop": "オフ",
  "nast.daljna": "遠くの銀河",
  "nast.daljnaOpis": "背景にもう一つの銀河",
  "nast.galaksijaOpis": "輝き、星の大きさ、速度",
  "nast.gibanje": "動き",
  "nast.odziv": "マウスへの反応",
  "nast.odzivOpis": "視点がカーソルを追う",
  "nast.kazalec": "カーソル",
  "nast.kazalecMeri": "カスタムカーソル",
  "nast.kazalecMeriOpis": "システムカーソルの代わりに火花",
  "nast.magnet": "マグネットボタン",
  "nast.magnetOpis": "ボタンがカーソルの方へ傾く",
  "nast.izris": "レンダリング",
  "nast.sij": "輝き",
  "nast.velikost": "星の大きさ",
  "nast.kamera": "カメラ",
  "nast.hitrost": "軌道の速さ",

  "zapis.zapri": "閉じる",
  "zapis.prejsnja": "前へ",
  "zapis.naslednja": "次へ",

  "viz.stran": "サイト",
  "viz.prizor": "シーン",
  "viz.prizorV": "銀河、50,000 点",
  "viz.izris": "レンダリング",
  "viz.izrisV": "WebGL、自作シェーダー",
  "viz.ogrodje": "フレームワーク",
  "viz.ogrodjeV": "Vite、フレームワークなし",
  "viz.galerija": "ギャラリー",
  "viz.objav": "投稿",
  "viz.maskota": "Jure Labs マスコット",
  "viz.zapri": "名刺を閉じる",
  "viz.ascii": "Jure Labs ASCII アニメーション",
  "viz.metaT": "オーダーメイドのウェブアプリ",
  "viz.metaS": "速く。確かに。効率よく。",

  "kmeni.novZavihek": "新しいタブで開く",
  "kmeni.kopiraj": "アドレスをコピー",
  "kmeni.profil": "プロフィール",
  "kmeni.nastavitve": "設定",
  "kmeni.ponastavi": "表示をリセット",

  "ogled.zapri": "画像を閉じる",
  "zemlja.slovenija": "スロベニア",

  "prof.zapri": "閉じる",
  "prof.objav": "投稿",
  "prof.sledilcev": "フォロワー",
  "prof.sledi": "フォロー中",
  "prof.bio": "✨ 星を捕まえられなかったら、君を迎えに行く。",
  "prof.uredi": "プロフィールを編集",
  "prof.arhiv": "アーカイブ",
  "prof.objave": "投稿",
  "prof.shranjeno": "保存済み",
  "prof.oznaceno": "タグ付け",
  "prof.razporeditev": "レイアウト",

  "gal.razpored.tri": "3 列",
  "gal.razpored.dve": "2 列",
  "gal.razpored.stiri": "4 列",
  "gal.razpored.mozaik": "モザイク",
  "gal.razpored.stopnice": "階段",
  "gal.razpored.gost": "高密度 (6–7)",
  "gal.razpored.trak": "帯",
  "gal.razpored.izvirno": "元の比率",
  "gal.razpored.izvirnoxl": "元の比率 XL",
  "gal.razpored.polno": "全画面",
  "gal.razpored.stolpci": "レンガ",
  "gal.razpored.prostor": "3D 空間",
  "gal.prostor.priblizaj": "拡大",
  "gal.prostor.oddalji": "縮小",
  "gal.razmik.da": "間隔あり",
  "gal.razmik.ne": "間隔なし",
  "gal.sirina.robovi": "端まで",
  "gal.sirina.cez": "ワイド",
  "gal.sirina.sredina": "中央",
};
