/** 한국어 - vmesnik. Besedila strani ostanejo slovenska, dokler niso prevedena. */
export default {
  "jezik.naslov": "언어",
  "profil.aria": "프로필",
  "meni.aria": "메인 메뉴",
  "meni.arhiv": "보관함",
  "meni.delo": "작업",
  "meni.omeni": "소개",
  "meni.stik": "연락처",
  "orodja.aria": "도구",
  "orodja.iskanje": "검색",
  "orodja.nastavitve": "설정",

  "nast.naslov": "설정",
  "nast.nazaj": "뒤로",
  "nast.zapri": "닫기",
  "nast.videz": "모양",
  "nast.jezik": "언어",
  "nast.prosojnost": "투명도",
  "nast.tema": "테마",
  "nast.temna": "다크",
  "nast.svetla": "라이트",
  "nast.sistem": "시스템",
  "nast.ozadje": "배경",
  "nast.prizor": "장면",
  "nast.galaksija": "은하",
  "nast.zvezde": "별만",
  "nast.izklop": "끄기",
  "nast.daljna": "먼 은하",
  "nast.daljnaOpis": "배경의 두 번째 은하",
  "nast.galaksijaOpis": "광채, 별 크기, 속도",
  "nast.gibanje": "움직임",
  "nast.odziv": "마우스 반응",
  "nast.odzivOpis": "화면이 커서를 따라감",
  "nast.kazalec": "커서",
  "nast.kazalecMeri": "사용자 커서",
  "nast.kazalecMeriOpis": "시스템 커서 대신 불꽃",
  "nast.magnet": "자석 버튼",
  "nast.magnetOpis": "버튼이 커서 쪽으로 기울어짐",
  "nast.izris": "렌더링",
  "nast.sij": "광채",
  "nast.velikost": "별 크기",
  "nast.kamera": "카메라",
  "nast.hitrost": "궤도 속도",

  "zapis.zapri": "닫기",
  "zapis.prejsnja": "이전",
  "zapis.naslednja": "다음",

  "viz.stran": "사이트",
  "viz.prizor": "장면",
  "viz.prizorV": "은하, 50,000개 점",
  "viz.izris": "렌더링",
  "viz.izrisV": "WebGL, 자체 셰이더",
  "viz.ogrodje": "프레임워크",
  "viz.ogrodjeV": "Vite, 프레임워크 없음",
  "viz.galerija": "갤러리",
  "viz.objav": "게시물",
  "viz.maskota": "Jure Labs 마스코트",
  "viz.zapri": "명함 닫기",
  "viz.ascii": "Jure Labs ASCII 애니메이션",
  "viz.metaT": "맞춤형 웹 앱",
  "viz.metaS": "빠르게. 믿을 수 있게. 효율적으로.",

  "kmeni.novZavihek": "새 탭에서 열기",
  "kmeni.kopiraj": "주소 복사",
  "kmeni.profil": "프로필",
  "kmeni.nastavitve": "설정",
  "kmeni.ponastavi": "화면 초기화",

  "ogled.zapri": "이미지 닫기",
  "zemlja.slovenija": "슬로베니아",

  "prof.zapri": "닫기",
  "prof.objav": "게시물",
  "prof.sledilcev": "팔로워",
  "prof.sledi": "팔로잉",
  "prof.bio": "✨ 별을 잡지 못하면, 너를 데리러 갈게.",
  "prof.uredi": "프로필 편집",
  "prof.arhiv": "보관함",
  "prof.objave": "게시물",
  "prof.shranjeno": "저장됨",
  "prof.oznaceno": "태그됨",
  "prof.razporeditev": "레이아웃",

  "gal.razpored.tri": "3열",
  "gal.razpored.dve": "2열",
  "gal.razpored.stiri": "4열",
  "gal.razpored.mozaik": "모자이크",
  "gal.razpored.stopnice": "계단",
  "gal.razpored.gost": "촘촘히 (6–7)",
  "gal.razpored.trak": "띠",
  "gal.razpored.izvirno": "원본 비율",
  "gal.razpored.izvirnoxl": "원본 비율 XL",
  "gal.razpored.polno": "전체 화면",
  "gal.razpored.stolpci": "벽돌",
  "gal.razpored.prostor": "3D 공간",
  "gal.prostor.priblizaj": "확대",
  "gal.prostor.oddalji": "축소",
  "gal.razmik.da": "간격 있음",
  "gal.razmik.ne": "간격 없음",
  "gal.sirina.robovi": "가장자리까지",
  "gal.sirina.cez": "넓게",
  "gal.sirina.sredina": "가운데",
};
