/** Македонски - vmesnik. Besedila strani ostanejo slovenska, dokler niso prevedena. */
export default {
  "jezik.naslov": "Јазик",
  "profil.aria": "Профил",
  "meni.aria": "Главно мени",
  "meni.arhiv": "Архива",
  "meni.delo": "Работа",
  "meni.omeni": "За мене",
  "meni.stik": "Контакт",
  "orodja.aria": "Алатки",
  "orodja.iskanje": "Пребарување",
  "orodja.nastavitve": "Поставки",

  "nast.naslov": "Поставки",
  "nast.nazaj": "Назад",
  "nast.zapri": "Затвори",
  "nast.videz": "Изглед",
  "nast.jezik": "Јазик",
  "nast.prosojnost": "Проѕирност",
  "nast.tema": "Тема",
  "nast.temna": "Темна",
  "nast.svetla": "Светла",
  "nast.sistem": "Според системот",
  "nast.ozadje": "Позадина",
  "nast.prizor": "Сцена",
  "nast.galaksija": "Галаксија",
  "nast.zvezde": "Само ѕвезди",
  "nast.izklop": "Исклучено",
  "nast.daljna": "Далечна галаксија",
  "nast.daljnaOpis": "Втора галаксија во позадина",
  "nast.galaksijaOpis": "Сјај, големина на ѕвездите, брзина",
  "nast.gibanje": "Движење",
  "nast.odziv": "Одзив на глувчето",
  "nast.odzivOpis": "Погледот го следи покажувачот",
  "nast.kazalec": "Покажувач",
  "nast.kazalecMeri": "Сопствен покажувач",
  "nast.kazalecMeriOpis": "Искра наместо системскиот покажувач",
  "nast.magnet": "Магнетни копчиња",
  "nast.magnetOpis": "Копчињата се навалуваат кон покажувачот",
  "nast.izris": "Исцртување",
  "nast.sij": "Сјај",
  "nast.velikost": "Големина на ѕвездите",
  "nast.kamera": "Камера",
  "nast.hitrost": "Брзина на орбитата",

  "zapis.zapri": "Затвори",
  "zapis.prejsnja": "Претходна",
  "zapis.naslednja": "Следна",

  "viz.stran": "СТРАНИЦА",
  "viz.prizor": "СЦЕНА",
  "viz.prizorV": "галаксија, 50 000 точки",
  "viz.izris": "ИСЦРТУВАЊЕ",
  "viz.izrisV": "WebGL, сопствен шејдер",
  "viz.ogrodje": "РАМКА",
  "viz.ogrodjeV": "Vite, без рамка",
  "viz.galerija": "ГАЛЕРИЈА",
  "viz.objav": "објави",
  "viz.maskota": "Маскота на Jure Labs",
  "viz.zapri": "Затвори ја визит-картата",
  "viz.ascii": "ASCII анимација на Jure Labs",
  "viz.metaT": "Веб-апликации по мерка",
  "viz.metaS": "Брзи. Сигурни. Ефикасни.",

  "kmeni.novZavihek": "Отвори во нова картичка",
  "kmeni.kopiraj": "Копирај адреса",
  "kmeni.profil": "Профил",
  "kmeni.nastavitve": "Поставки",
  "kmeni.ponastavi": "Ресетирај поглед",

  "ogled.zapri": "Затвори слика",
  "zemlja.slovenija": "Словенија",

  "prof.zapri": "Затвори",
  "prof.objav": "објави",
  "prof.sledilcev": "следбеници",
  "prof.sledi": "следи",
  "prof.bio": "✨ Ако не ги фатам ѕвездите, ќе дојдам по тебе.",
  "prof.uredi": "Уреди профил",
  "prof.arhiv": "Архива",
  "prof.objave": "Објави",
  "prof.shranjeno": "Зачувано",
  "prof.oznaceno": "Означено",
  "prof.razporeditev": "Распоред",

  "gal.razpored.tri": "Три колони",
  "gal.razpored.dve": "Две колони",
  "gal.razpored.stiri": "Четири колони",
  "gal.razpored.mozaik": "Мозаик",
  "gal.razpored.stopnice": "Скали",
  "gal.razpored.gost": "Густо (6–7)",
  "gal.razpored.trak": "Лента",
  "gal.razpored.izvirno": "Оригинални пропорции",
  "gal.razpored.izvirnoxl": "Оригинални пропорции XL",
  "gal.razpored.polno": "Цел екран",
  "gal.razpored.stolpci": "Тули",
  "gal.razpored.prostor": "3Д простор",
  "gal.prostor.priblizaj": "Приближи",
  "gal.prostor.oddalji": "Оддалечи",
  "gal.razmik.da": "Со простор",
  "gal.razmik.ne": "Без простор",
  "gal.sirina.robovi": "До рабовите",
  "gal.sirina.cez": "Широко",
  "gal.sirina.sredina": "Во средина",
};
