/** Nederlands - vmesnik. Besedila strani ostanejo slovenska, dokler niso prevedena. */
export default {
  "jezik.naslov": "Taal",
  "profil.aria": "Profiel",
  "meni.aria": "Hoofdmenu",
  "meni.arhiv": "Archief",
  "meni.delo": "Werk",
  "meni.omeni": "Over mij",
  "meni.stik": "Contact",
  "orodja.aria": "Hulpmiddelen",
  "orodja.iskanje": "Zoeken",
  "orodja.nastavitve": "Instellingen",

  "nast.naslov": "Instellingen",
  "nast.nazaj": "Terug",
  "nast.zapri": "Sluiten",
  "nast.videz": "Weergave",
  "nast.jezik": "Taal",
  "nast.prosojnost": "Transparantie",
  "nast.tema": "Thema",
  "nast.temna": "Donker",
  "nast.svetla": "Licht",
  "nast.sistem": "Systeem",
  "nast.ozadje": "Achtergrond",
  "nast.prizor": "Scène",
  "nast.galaksija": "Sterrenstelsel",
  "nast.zvezde": "Alleen sterren",
  "nast.izklop": "Uit",
  "nast.daljna": "Ver sterrenstelsel",
  "nast.daljnaOpis": "Een tweede sterrenstelsel op de achtergrond",
  "nast.galaksijaOpis": "Gloed, stergrootte, snelheid",
  "nast.gibanje": "Beweging",
  "nast.odziv": "Reactie op muis",
  "nast.odzivOpis": "Het beeld volgt de cursor",
  "nast.kazalec": "Cursor",
  "nast.kazalecMeri": "Eigen cursor",
  "nast.kazalecMeriOpis": "Een vonk in plaats van de systeemcursor",
  "nast.magnet": "Magnetische knoppen",
  "nast.magnetOpis": "Knoppen buigen naar de cursor",
  "nast.izris": "Rendering",
  "nast.sij": "Gloed",
  "nast.velikost": "Stergrootte",
  "nast.kamera": "Camera",
  "nast.hitrost": "Baansnelheid",

  "zapis.zapri": "Sluiten",
  "zapis.prejsnja": "Vorige",
  "zapis.naslednja": "Volgende",
  "zapis.odpri": "App openen",
  "aplikacija.demo": "Demoversie · de gegevens zijn verzonnen",
  "aplikacija.zavihek": "Openen in nieuw tabblad",
  "aplikacija.zapri": "App sluiten",

  "viz.stran": "SITE",
  "viz.prizor": "SCÈNE",
  "viz.prizorV": "sterrenstelsel, 50.000 punten",
  "viz.izris": "RENDERING",
  "viz.izrisV": "WebGL, eigen shader",
  "viz.ogrodje": "FRAMEWORK",
  "viz.ogrodjeV": "Vite, geen framework",
  "viz.galerija": "GALERIJ",
  "viz.objav": "berichten",
  "viz.maskota": "Mascotte van Jure Labs",
  "viz.zapri": "Visitekaartje sluiten",
  "viz.ascii": "ASCII-animatie van Jure Labs",
  "viz.metaT": "Webapplicaties op maat",
  "viz.metaS": "Snel. Betrouwbaar. Efficiënt.",

  "kmeni.novZavihek": "Openen in nieuw tabblad",
  "kmeni.kopiraj": "Adres kopiëren",
  "kmeni.profil": "Profiel",
  "kmeni.nastavitve": "Instellingen",
  "kmeni.ponastavi": "Weergave herstellen",

  "ogled.zapri": "Afbeelding sluiten",
  "zemlja.slovenija": "Slovenië",

  "prof.zapri": "Sluiten",
  "prof.objav": "berichten",
  "prof.sledilcev": "volgers",
  "prof.sledi": "volgend",
  "prof.bio": "✨ Als ik de sterren niet vang, kom ik jou halen.",
  "prof.uredi": "Profiel bewerken",
  "prof.arhiv": "Archief",
  "prof.objave": "Berichten",
  "prof.shranjeno": "Opgeslagen",
  "prof.oznaceno": "Getagd",
  "prof.razporeditev": "Indeling",

  "gal.razpored.tri": "Drie kolommen",
  "gal.razpored.dve": "Twee kolommen",
  "gal.razpored.stiri": "Vier kolommen",
  "gal.razpored.mozaik": "Mozaïek",
  "gal.razpored.stopnice": "Trappen",
  "gal.razpored.gost": "Dicht (6–7)",
  "gal.razpored.trak": "Strook",
  "gal.razpored.izvirno": "Originele verhoudingen",
  "gal.razpored.izvirnoxl": "Originele verhoudingen XL",
  "gal.razpored.polno": "Volledig scherm",
  "gal.razpored.stolpci": "Metselwerk",
  "gal.razpored.prostor": "3D-ruimte",
  "gal.prostor.priblizaj": "Inzoomen",
  "gal.prostor.oddalji": "Uitzoomen",
  "gal.razmik.da": "Met ruimte",
  "gal.razmik.ne": "Zonder ruimte",
  "gal.sirina.robovi": "Tot de randen",
  "gal.sirina.cez": "Breed",
  "gal.sirina.sredina": "Gecentreerd",
};
