/** Norsk - vmesnik. Besedila strani ostanejo slovenska, dokler niso prevedena. */
export default {
  "jezik.naslov": "Språk",
  "profil.aria": "Profil",
  "meni.aria": "Hovedmeny",
  "meni.arhiv": "Arkiv",
  "meni.delo": "Arbeid",
  "meni.omeni": "Om meg",
  "meni.stik": "Kontakt",
  "orodja.aria": "Verktøy",
  "orodja.iskanje": "Søk",
  "orodja.nastavitve": "Innstillinger",

  "nast.naslov": "Innstillinger",
  "nast.nazaj": "Tilbake",
  "nast.zapri": "Lukk",
  "nast.videz": "Utseende",
  "nast.jezik": "Språk",
  "nast.prosojnost": "Gjennomsiktighet",
  "nast.tema": "Tema",
  "nast.temna": "Mørkt",
  "nast.svetla": "Lyst",
  "nast.sistem": "System",
  "nast.ozadje": "Bakgrunn",
  "nast.prizor": "Scene",
  "nast.galaksija": "Galakse",
  "nast.zvezde": "Bare stjerner",
  "nast.izklop": "Av",
  "nast.daljna": "Fjern galakse",
  "nast.daljnaOpis": "En annen galakse i bakgrunnen",
  "nast.galaksijaOpis": "Glød, stjernestørrelse, fart",
  "nast.gibanje": "Bevegelse",
  "nast.odziv": "Musrespons",
  "nast.odzivOpis": "Visningen følger markøren",
  "nast.kazalec": "Markør",
  "nast.kazalecMeri": "Egen markør",
  "nast.kazalecMeriOpis": "En gnist i stedet for systemmarkøren",
  "nast.magnet": "Magnetiske knapper",
  "nast.magnetOpis": "Knappene lener seg mot markøren",
  "nast.izris": "Gjengivelse",
  "nast.sij": "Glød",
  "nast.velikost": "Stjernestørrelse",
  "nast.kamera": "Kamera",
  "nast.hitrost": "Banefart",

  "zapis.zapri": "Lukk",
  "zapis.prejsnja": "Forrige",
  "zapis.naslednja": "Neste",
  "zapis.odpri": "Åpne appen",
  "aplikacija.demo": "Demoversjon · dataene er oppdiktet",
  "aplikacija.zavihek": "Åpne i ny fane",
  "aplikacija.zapri": "Lukk appen",

  "viz.stran": "NETTSTED",
  "viz.prizor": "SCENE",
  "viz.prizorV": "galakse, 50 000 punkter",
  "viz.izris": "GJENGIVELSE",
  "viz.izrisV": "WebGL, egen shader",
  "viz.ogrodje": "RAMMEVERK",
  "viz.ogrodjeV": "Vite, uten rammeverk",
  "viz.galerija": "GALLERI",
  "viz.objav": "innlegg",
  "viz.maskota": "Jure Labs-maskot",
  "viz.zapri": "Lukk visittkortet",
  "viz.ascii": "Jure Labs ASCII-animasjon",
  "viz.metaT": "Skreddersydde nettapper",
  "viz.metaS": "Raske. Pålitelige. Effektive.",

  "kmeni.novZavihek": "Åpne i ny fane",
  "kmeni.kopiraj": "Kopier adresse",
  "kmeni.profil": "Profil",
  "kmeni.nastavitve": "Innstillinger",
  "kmeni.ponastavi": "Tilbakestill visning",

  "ogled.zapri": "Lukk bildet",
  "zemlja.slovenija": "Slovenia",

  "prof.zapri": "Lukk",
  "prof.objav": "innlegg",
  "prof.sledilcev": "følgere",
  "prof.sledi": "følger",
  "prof.bio": "✨ Hvis jeg ikke fanger stjernene, kommer jeg etter deg.",
  "prof.uredi": "Rediger profil",
  "prof.arhiv": "Arkiv",
  "prof.objave": "Innlegg",
  "prof.shranjeno": "Lagret",
  "prof.oznaceno": "Merket",
  "prof.razporeditev": "Oppsett",

  "gal.razpored.tri": "Tre kolonner",
  "gal.razpored.dve": "To kolonner",
  "gal.razpored.stiri": "Fire kolonner",
  "gal.razpored.mozaik": "Mosaikk",
  "gal.razpored.stopnice": "Trinn",
  "gal.razpored.gost": "Tett (6–7)",
  "gal.razpored.trak": "Stripe",
  "gal.razpored.izvirno": "Originale proporsjoner",
  "gal.razpored.izvirnoxl": "Originale proporsjoner XL",
  "gal.razpored.polno": "Fullskjerm",
  "gal.razpored.stolpci": "Murstein",
  "gal.razpored.prostor": "3D-rom",
  "gal.prostor.priblizaj": "Zoom inn",
  "gal.prostor.oddalji": "Zoom ut",
  "gal.razmik.da": "Med mellomrom",
  "gal.razmik.ne": "Uten mellomrom",
  "gal.sirina.robovi": "Kant til kant",
  "gal.sirina.cez": "Bredt",
  "gal.sirina.sredina": "Sentrert",
};
