/** Polski - vmesnik. Besedila strani ostanejo slovenska, dokler niso prevedena. */
export default {
  "jezik.naslov": "Język",
  "profil.aria": "Profil",
  "meni.aria": "Menu główne",
  "meni.arhiv": "Archiwum",
  "meni.delo": "Praca",
  "meni.omeni": "O mnie",
  "meni.stik": "Kontakt",
  "orodja.aria": "Narzędzia",
  "orodja.iskanje": "Szukaj",
  "orodja.nastavitve": "Ustawienia",
  "orodja.arkada": "Salon gier",

  "nast.naslov": "Ustawienia",
  "nast.nazaj": "Wstecz",
  "nast.zapri": "Zamknij",
  "nast.videz": "Wygląd",
  "nast.jezik": "Język",
  "nast.prosojnost": "Przezroczystość",
  "nast.tema": "Motyw",
  "nast.temna": "Ciemny",
  "nast.svetla": "Jasny",
  "nast.sistem": "Systemowy",
  "nast.ozadje": "Tło",
  "nast.prizor": "Scena",
  "nast.galaksija": "Galaktyka",
  "nast.zvezde": "Tylko gwiazdy",
  "nast.izklop": "Wyłączone",
  "nast.daljna": "Odległa galaktyka",
  "nast.daljnaOpis": "Druga galaktyka w tle",
  "nast.galaksijaOpis": "Poświata, rozmiar gwiazd, prędkość",
  "nast.gibanje": "Ruch",
  "nast.odziv": "Reakcja na mysz",
  "nast.odzivOpis": "Widok podąża za kursorem",
  "nast.kazalec": "Kursor",
  "nast.kazalecMeri": "Własny kursor",
  "nast.kazalecMeriOpis": "Iskra zamiast kursora systemowego",
  "nast.magnet": "Magnetyczne przyciski",
  "nast.magnetOpis": "Przyciski przechylają się w stronę kursora",
  "nast.izris": "Renderowanie",
  "nast.sij": "Poświata",
  "nast.velikost": "Rozmiar gwiazd",
  "nast.kamera": "Kamera",
  "nast.hitrost": "Prędkość orbity",

  "zapis.zapri": "Zamknij",
  "zapis.prejsnja": "Poprzednia",
  "zapis.naslednja": "Następna",
  "zapis.odpri": "Otwórz aplikację",
  "zapis.seVec": "i więcej",
  "aplikacija.demo": "Wersja demo · dane są zmyślone",
  "aplikacija.zavihek": "Otwórz w nowej karcie",
  "aplikacija.zapri": "Zamknij aplikację",

  "viz.stran": "STRONA",
  "viz.prizor": "SCENA",
  "viz.prizorV": "galaktyka, 50 000 punktów",
  "viz.izris": "RENDEROWANIE",
  "viz.izrisV": "WebGL, własny shader",
  "viz.ogrodje": "FRAMEWORK",
  "viz.ogrodjeV": "Vite, bez frameworka",
  "viz.galerija": "GALERIA",
  "viz.objav": "postów",
  "viz.maskota": "Maskotka Jure Labs",
  "viz.zapri": "Zamknij wizytówkę",
  "viz.ascii": "Animacja ASCII Jure Labs",
  "viz.metaT": "Aplikacje webowe na zamówienie",
  "viz.metaS": "Szybkie. Niezawodne. Wydajne.",

  "kmeni.novZavihek": "Otwórz w nowej karcie",
  "kmeni.kopiraj": "Kopiuj adres",
  "kmeni.profil": "Profil",
  "kmeni.nastavitve": "Ustawienia",
  "kmeni.ponastavi": "Resetuj widok",
  "kmeni.kopirajBesedilo": "Kopiuj",
  "kmeni.kopirajPovezavo": "Kopiuj link",
  "kmeni.kopirajEposto": "Kopiuj adres e-mail",
  "kmeni.odpriSliko": "Otwórz obraz",
  "kmeni.kopirajSliko": "Kopiuj adres obrazu",
  "kmeni.jezik": "Język",
  "kmeni.kopirajStran": "Kopiuj link do strony",
  "kmeni.celozaslonsko": "Pełny ekran",
  "kmeni.izhodCelozaslonsko": "Zamknij pełny ekran",
  "arkada.naslov": "Salon gier",
  "arkada.kmalu": "Wkrótce",
  "arkada.opis": "Minigry są w drodze. Wkrótce zagrasz w nie właśnie tutaj.",

  "ogled.zapri": "Zamknij obraz",
  "zemlja.slovenija": "Słowenia",

  "prof.zapri": "Zamknij",
  "prof.objav": "postów",
  "prof.sledilcev": "obserwujących",
  "prof.sledi": "obserwowanych",
  "prof.uredi": "Edytuj profil",
  "prof.arhiv": "Archiwum",
  "prof.objave": "Posty",
  "prof.shranjeno": "Zapisane",
  "prof.oznaceno": "Oznaczone",
  "prof.razporeditev": "Układ",

  "gal.razpored.tri": "Trzy kolumny",
  "gal.razpored.dve": "Dwie kolumny",
  "gal.razpored.stiri": "Cztery kolumny",
  "gal.razpored.mozaik": "Mozaika",
  "gal.razpored.stopnice": "Schodki",
  "gal.razpored.gost": "Gęsto (6–7)",
  "gal.razpored.trak": "Pasek",
  "gal.razpored.izvirno": "Oryginalne proporcje",
  "gal.razpored.izvirnoxl": "Oryginalne proporcje XL",
  "gal.razpored.polno": "Pełny ekran",
  "gal.razpored.stolpci": "Cegła",
  "gal.razpored.prostor": "Przestrzeń 3D",
  "gal.prostor.priblizaj": "Przybliż",
  "gal.prostor.oddalji": "Oddal",
  "gal.razmik.da": "Z odstępem",
  "gal.razmik.ne": "Bez odstępu",
  "gal.sirina.robovi": "Do krawędzi",
  "gal.sirina.cez": "Szeroko",
  "gal.sirina.sredina": "Na środku",
};
