/** Português (Brasil) - vmesnik. Besedila strani ostanejo slovenska, dokler niso prevedena. */
export default {
  "jezik.naslov": "Idioma",
  "profil.aria": "Perfil",
  "meni.aria": "Menu principal",
  "meni.arhiv": "Arquivo",
  "meni.delo": "Trabalho",
  "meni.omeni": "Sobre mim",
  "meni.stik": "Contato",
  "orodja.aria": "Ferramentas",
  "orodja.iskanje": "Pesquisar",
  "orodja.nastavitve": "Configurações",
  "orodja.arkada": "Arcada",

  "nast.naslov": "Configurações",
  "nast.nazaj": "Voltar",
  "nast.zapri": "Fechar",
  "nast.videz": "Aparência",
  "nast.jezik": "Idioma",
  "nast.prosojnost": "Transparência",
  "nast.tema": "Tema",
  "nast.temna": "Escuro",
  "nast.svetla": "Claro",
  "nast.sistem": "Sistema",
  "nast.ozadje": "Fundo",
  "nast.prizor": "Cena",
  "nast.galaksija": "Galáxia",
  "nast.zvezde": "Só estrelas",
  "nast.izklop": "Desligado",
  "nast.daljna": "Galáxia distante",
  "nast.daljnaOpis": "Uma segunda galáxia ao fundo",
  "nast.galaksijaOpis": "Brilho, tamanho das estrelas, velocidade",
  "nast.gibanje": "Movimento",
  "nast.odziv": "Resposta ao mouse",
  "nast.odzivOpis": "A vista segue o cursor",
  "nast.kazalec": "Cursor",
  "nast.kazalecMeri": "Cursor personalizado",
  "nast.kazalecMeriOpis": "Uma faísca em vez do cursor do sistema",
  "nast.magnet": "Botões magnéticos",
  "nast.magnetOpis": "Os botões se inclinam em direção ao cursor",
  "nast.izris": "Renderização",
  "nast.sij": "Brilho",
  "nast.velikost": "Tamanho das estrelas",
  "nast.kamera": "Câmera",
  "nast.hitrost": "Velocidade da órbita",

  "zapis.zapri": "Fechar",
  "zapis.prejsnja": "Anterior",
  "zapis.naslednja": "Próxima",
  "zapis.odpri": "Abrir app",
  "zapis.seVec": "e mais",
  "aplikacija.demo": "Versão demo · os dados são fictícios",
  "aplikacija.zavihek": "Abrir num novo separador",
  "aplikacija.zapri": "Fechar app",

  "viz.stran": "SITE",
  "viz.prizor": "CENA",
  "viz.prizorV": "galáxia, 50.000 pontos",
  "viz.izris": "RENDERIZAÇÃO",
  "viz.izrisV": "WebGL, shader próprio",
  "viz.ogrodje": "FRAMEWORK",
  "viz.ogrodjeV": "Vite, sem framework",
  "viz.galerija": "GALERIA",
  "viz.objav": "publicações",
  "viz.maskota": "Mascote da Jure Labs",
  "viz.zapri": "Fechar cartão de visita",
  "viz.ascii": "Animação ASCII da Jure Labs",
  "viz.metaT": "Aplicações web sob medida",
  "viz.metaS": "Rápidas. Confiáveis. Eficientes.",

  "kmeni.novZavihek": "Abrir em nova aba",
  "kmeni.kopiraj": "Copiar endereço",
  "kmeni.profil": "Perfil",
  "kmeni.nastavitve": "Configurações",
  "kmeni.ponastavi": "Redefinir visualização",
  "kmeni.kopirajBesedilo": "Copiar",
  "kmeni.kopirajPovezavo": "Copiar link",
  "kmeni.kopirajEposto": "Copiar endereço de e-mail",
  "kmeni.odpriSliko": "Abrir imagem",
  "kmeni.kopirajSliko": "Copiar endereço da imagem",
  "kmeni.jezik": "Idioma",
  "kmeni.kopirajStran": "Copiar link da página",
  "kmeni.celozaslonsko": "Ecrã inteiro",
  "kmeni.izhodCelozaslonsko": "Sair do ecrã inteiro",
  "arkada.naslov": "Arcada",
  "arkada.kmalu": "Em breve",
  "arkada.opis": "Os minijogos estão a caminho. Em breve vais poder jogá-los aqui mesmo.",

  "ogled.zapri": "Fechar imagem",
  "zemlja.slovenija": "Eslovênia",

  "prof.zapri": "Fechar",
  "prof.objav": "publicações",
  "prof.sledilcev": "seguidores",
  "prof.sledi": "seguindo",
  "prof.bio": "✨ Se eu não pegar as estrelas, vou atrás de você.",
  "prof.uredi": "Editar perfil",
  "prof.arhiv": "Arquivo",
  "prof.objave": "Publicações",
  "prof.shranjeno": "Salvos",
  "prof.oznaceno": "Marcados",
  "prof.razporeditev": "Layout",

  "gal.razpored.tri": "Três colunas",
  "gal.razpored.dve": "Duas colunas",
  "gal.razpored.stiri": "Quatro colunas",
  "gal.razpored.mozaik": "Mosaico",
  "gal.razpored.stopnice": "Degraus",
  "gal.razpored.gost": "Denso (6–7)",
  "gal.razpored.trak": "Faixa",
  "gal.razpored.izvirno": "Proporções originais",
  "gal.razpored.izvirnoxl": "Proporções originais XL",
  "gal.razpored.polno": "Tela cheia",
  "gal.razpored.stolpci": "Tijolos",
  "gal.razpored.prostor": "Espaço 3D",
  "gal.prostor.priblizaj": "Aproximar",
  "gal.prostor.oddalji": "Afastar",
  "gal.razmik.da": "Com espaçamento",
  "gal.razmik.ne": "Sem espaçamento",
  "gal.sirina.robovi": "De ponta a ponta",
  "gal.sirina.cez": "Largo",
  "gal.sirina.sredina": "Centralizado",
};
