/** Română - vmesnik. Besedila strani ostanejo slovenska, dokler niso prevedena. */
export default {
  "jezik.naslov": "Limbă",
  "profil.aria": "Profil",
  "meni.aria": "Meniu principal",
  "meni.arhiv": "Arhivă",
  "meni.delo": "Muncă",
  "meni.omeni": "Despre mine",
  "meni.stik": "Contact",
  "orodja.aria": "Instrumente",
  "orodja.iskanje": "Căutare",
  "orodja.nastavitve": "Setări",

  "nast.naslov": "Setări",
  "nast.nazaj": "Înapoi",
  "nast.zapri": "Închide",
  "nast.videz": "Aspect",
  "nast.jezik": "Limbă",
  "nast.prosojnost": "Transparență",
  "nast.tema": "Temă",
  "nast.temna": "Întunecată",
  "nast.svetla": "Luminoasă",
  "nast.sistem": "Sistem",
  "nast.ozadje": "Fundal",
  "nast.prizor": "Scenă",
  "nast.galaksija": "Galaxie",
  "nast.zvezde": "Doar stele",
  "nast.izklop": "Oprit",
  "nast.daljna": "Galaxie îndepărtată",
  "nast.daljnaOpis": "O a doua galaxie în fundal",
  "nast.galaksijaOpis": "Strălucire, mărimea stelelor, viteză",
  "nast.gibanje": "Mișcare",
  "nast.odziv": "Reacție la mouse",
  "nast.odzivOpis": "Vederea urmărește cursorul",
  "nast.kazalec": "Cursor",
  "nast.kazalecMeri": "Cursor personalizat",
  "nast.kazalecMeriOpis": "O scânteie în locul cursorului de sistem",
  "nast.magnet": "Butoane magnetice",
  "nast.magnetOpis": "Butoanele se înclină spre cursor",
  "nast.izris": "Randare",
  "nast.sij": "Strălucire",
  "nast.velikost": "Mărimea stelelor",
  "nast.kamera": "Cameră",
  "nast.hitrost": "Viteza orbitei",

  "zapis.zapri": "Închide",
  "zapis.prejsnja": "Anterioara",
  "zapis.naslednja": "Următoarea",

  "viz.stran": "SITE",
  "viz.prizor": "SCENĂ",
  "viz.prizorV": "galaxie, 50.000 de puncte",
  "viz.izris": "RANDARE",
  "viz.izrisV": "WebGL, shader propriu",
  "viz.ogrodje": "FRAMEWORK",
  "viz.ogrodjeV": "Vite, fără framework",
  "viz.galerija": "GALERIE",
  "viz.objav": "postări",
  "viz.maskota": "Mascota Jure Labs",
  "viz.zapri": "Închide cartea de vizită",
  "viz.ascii": "Animație ASCII Jure Labs",
  "viz.metaT": "Aplicații web la comandă",
  "viz.metaS": "Rapide. Fiabile. Eficiente.",

  "kmeni.novZavihek": "Deschide într-o filă nouă",
  "kmeni.kopiraj": "Copiază adresa",
  "kmeni.profil": "Profil",
  "kmeni.nastavitve": "Setări",
  "kmeni.ponastavi": "Resetează vederea",

  "ogled.zapri": "Închide imaginea",
  "zemlja.slovenija": "Slovenia",

  "prof.zapri": "Închide",
  "prof.objav": "postări",
  "prof.sledilcev": "urmăritori",
  "prof.sledi": "urmăriți",
  "prof.bio": "✨ Dacă nu prind stelele, vin după tine.",
  "prof.uredi": "Editează profilul",
  "prof.arhiv": "Arhivă",
  "prof.objave": "Postări",
  "prof.shranjeno": "Salvate",
  "prof.oznaceno": "Etichetate",
  "prof.razporeditev": "Aranjare",

  "gal.razpored.tri": "Trei coloane",
  "gal.razpored.dve": "Două coloane",
  "gal.razpored.stiri": "Patru coloane",
  "gal.razpored.mozaik": "Mozaic",
  "gal.razpored.stopnice": "Trepte",
  "gal.razpored.gost": "Dens (6–7)",
  "gal.razpored.trak": "Bandă",
  "gal.razpored.izvirno": "Proporții originale",
  "gal.razpored.izvirnoxl": "Proporții originale XL",
  "gal.razpored.polno": "Ecran complet",
  "gal.razpored.stolpci": "Cărămidă",
  "gal.razmik.da": "Cu spațiere",
  "gal.razmik.ne": "Fără spațiere",
  "gal.sirina.robovi": "Până la margini",
  "gal.sirina.cez": "Lat",
  "gal.sirina.sredina": "Centrat",
};
