/** Русский - vmesnik. Besedila strani ostanejo slovenska, dokler niso prevedena. */
export default {
  "jezik.naslov": "Язык",
  "profil.aria": "Профиль",
  "meni.aria": "Главное меню",
  "meni.arhiv": "Архив",
  "meni.delo": "Работа",
  "meni.omeni": "Обо мне",
  "meni.stik": "Контакт",
  "orodja.aria": "Инструменты",
  "orodja.iskanje": "Поиск",
  "orodja.nastavitve": "Настройки",

  "nast.naslov": "Настройки",
  "nast.nazaj": "Назад",
  "nast.zapri": "Закрыть",
  "nast.videz": "Внешний вид",
  "nast.jezik": "Язык",
  "nast.prosojnost": "Прозрачность",
  "nast.tema": "Тема",
  "nast.temna": "Тёмная",
  "nast.svetla": "Светлая",
  "nast.sistem": "Как в системе",
  "nast.ozadje": "Фон",
  "nast.prizor": "Сцена",
  "nast.galaksija": "Галактика",
  "nast.zvezde": "Только звёзды",
  "nast.izklop": "Выключено",
  "nast.daljna": "Далёкая галактика",
  "nast.daljnaOpis": "Вторая галактика на фоне",
  "nast.galaksijaOpis": "Сияние, размер звёзд, скорость",
  "nast.gibanje": "Движение",
  "nast.odziv": "Реакция на мышь",
  "nast.odzivOpis": "Вид следует за курсором",
  "nast.kazalec": "Курсор",
  "nast.kazalecMeri": "Свой курсор",
  "nast.kazalecMeriOpis": "Искра вместо системного курсора",
  "nast.magnet": "Магнитные кнопки",
  "nast.magnetOpis": "Кнопки тянутся к курсору",
  "nast.izris": "Рендеринг",
  "nast.sij": "Сияние",
  "nast.velikost": "Размер звёзд",
  "nast.kamera": "Камера",
  "nast.hitrost": "Скорость орбиты",

  "zapis.zapri": "Закрыть",
  "zapis.prejsnja": "Предыдущая",
  "zapis.naslednja": "Следующая",

  "viz.stran": "САЙТ",
  "viz.prizor": "СЦЕНА",
  "viz.prizorV": "галактика, 50 000 точек",
  "viz.izris": "РЕНДЕРИНГ",
  "viz.izrisV": "WebGL, свой шейдер",
  "viz.ogrodje": "ФРЕЙМВОРК",
  "viz.ogrodjeV": "Vite, без фреймворка",
  "viz.galerija": "ГАЛЕРЕЯ",
  "viz.objav": "публикаций",
  "viz.maskota": "Талисман Jure Labs",
  "viz.zapri": "Закрыть визитку",
  "viz.ascii": "ASCII-анимация Jure Labs",
  "viz.metaT": "Веб-приложения на заказ",
  "viz.metaS": "Быстрые. Надёжные. Эффективные.",

  "kmeni.novZavihek": "Открыть в новой вкладке",
  "kmeni.kopiraj": "Копировать адрес",
  "kmeni.profil": "Профиль",
  "kmeni.nastavitve": "Настройки",
  "kmeni.ponastavi": "Сбросить вид",

  "ogled.zapri": "Закрыть изображение",
  "zemlja.slovenija": "Словения",

  "prof.zapri": "Закрыть",
  "prof.objav": "публикаций",
  "prof.sledilcev": "подписчиков",
  "prof.sledi": "подписки",
  "prof.bio": "✨ Если не поймаю звёзды, приду за тобой.",
  "prof.uredi": "Редактировать профиль",
  "prof.arhiv": "Архив",
  "prof.objave": "Публикации",
  "prof.shranjeno": "Сохранённое",
  "prof.oznaceno": "Отметки",
  "prof.razporeditev": "Макет",

  "gal.razpored.tri": "Три колонки",
  "gal.razpored.dve": "Две колонки",
  "gal.razpored.stiri": "Четыре колонки",
  "gal.razpored.mozaik": "Мозаика",
  "gal.razpored.stopnice": "Ступени",
  "gal.razpored.gost": "Плотно (6–7)",
  "gal.razpored.trak": "Лента",
  "gal.razpored.izvirno": "Исходные пропорции",
  "gal.razpored.izvirnoxl": "Исходные пропорции XL",
  "gal.razpored.polno": "Во весь экран",
  "gal.razpored.stolpci": "Кирпичи",
  "gal.razmik.da": "С отступом",
  "gal.razmik.ne": "Без отступа",
  "gal.sirina.robovi": "До краёв",
  "gal.sirina.cez": "Широко",
  "gal.sirina.sredina": "По центру",
};
