/** Slovenčina - vmesnik. Besedila strani ostanejo slovenska, dokler niso prevedena. */
export default {
  "jezik.naslov": "Jazyk",
  "profil.aria": "Profil",
  "meni.aria": "Hlavné menu",
  "meni.arhiv": "Archív",
  "meni.delo": "Práca",
  "meni.omeni": "O mne",
  "meni.stik": "Kontakt",
  "orodja.aria": "Nástroje",
  "orodja.iskanje": "Hľadať",
  "orodja.nastavitve": "Nastavenia",

  "nast.naslov": "Nastavenia",
  "nast.nazaj": "Späť",
  "nast.zapri": "Zavrieť",
  "nast.videz": "Vzhľad",
  "nast.jezik": "Jazyk",
  "nast.prosojnost": "Priehľadnosť",
  "nast.tema": "Motív",
  "nast.temna": "Tmavý",
  "nast.svetla": "Svetlý",
  "nast.sistem": "Podľa systému",
  "nast.ozadje": "Pozadie",
  "nast.prizor": "Scéna",
  "nast.galaksija": "Galaxia",
  "nast.zvezde": "Iba hviezdy",
  "nast.izklop": "Vypnuté",
  "nast.daljna": "Vzdialená galaxia",
  "nast.daljnaOpis": "Druhá galaxia v pozadí",
  "nast.galaksijaOpis": "Žiara, veľkosť hviezd, rýchlosť",
  "nast.gibanje": "Pohyb",
  "nast.odziv": "Reakcia na myš",
  "nast.odzivOpis": "Pohľad sleduje kurzor",
  "nast.kazalec": "Kurzor",
  "nast.kazalecMeri": "Vlastný kurzor",
  "nast.kazalecMeriOpis": "Iskra namiesto systémového kurzora",
  "nast.magnet": "Magnetické tlačidlá",
  "nast.magnetOpis": "Tlačidlá sa nakláňajú ku kurzoru",
  "nast.izris": "Vykresľovanie",
  "nast.sij": "Žiara",
  "nast.velikost": "Veľkosť hviezd",
  "nast.kamera": "Kamera",
  "nast.hitrost": "Rýchlosť obehu",

  "zapis.zapri": "Zavrieť",
  "zapis.prejsnja": "Predchádzajúca",
  "zapis.naslednja": "Ďalšia",
  "zapis.odpri": "Otvoriť aplikáciu",
  "aplikacija.demo": "Ukážková verzia · údaje sú vymyslené",
  "aplikacija.zavihek": "Otvoriť na novej karte",
  "aplikacija.zapri": "Zavrieť aplikáciu",

  "viz.stran": "WEB",
  "viz.prizor": "SCÉNA",
  "viz.prizorV": "galaxia, 50 000 bodov",
  "viz.izris": "VYKRESĽOVANIE",
  "viz.izrisV": "WebGL, vlastný shader",
  "viz.ogrodje": "FRAMEWORK",
  "viz.ogrodjeV": "Vite, bez frameworku",
  "viz.galerija": "GALÉRIA",
  "viz.objav": "príspevkov",
  "viz.maskota": "Maskot Jure Labs",
  "viz.zapri": "Zavrieť vizitku",
  "viz.ascii": "ASCII animácia Jure Labs",
  "viz.metaT": "Webové aplikácie na mieru",
  "viz.metaS": "Rýchle. Spoľahlivé. Efektívne.",

  "kmeni.novZavihek": "Otvoriť na novej karte",
  "kmeni.kopiraj": "Kopírovať adresu",
  "kmeni.profil": "Profil",
  "kmeni.nastavitve": "Nastavenia",
  "kmeni.ponastavi": "Obnoviť pohľad",
  "kmeni.kopirajBesedilo": "Kopírovať",
  "kmeni.kopirajPovezavo": "Kopírovať odkaz",
  "kmeni.kopirajEposto": "Kopírovať e-mailovú adresu",
  "kmeni.odpriSliko": "Otvoriť obrázok",
  "kmeni.kopirajSliko": "Kopírovať adresu obrázka",
  "kmeni.jezik": "Jazyk",
  "kmeni.kopirajStran": "Kopírovať odkaz na stránku",
  "kmeni.celozaslonsko": "Celá obrazovka",
  "kmeni.izhodCelozaslonsko": "Ukončiť celú obrazovku",

  "ogled.zapri": "Zavrieť obrázok",
  "zemlja.slovenija": "Slovinsko",

  "prof.zapri": "Zavrieť",
  "prof.objav": "príspevkov",
  "prof.sledilcev": "sledovateľov",
  "prof.sledi": "sleduje",
  "prof.bio": "✨ Ak nechytím hviezdy, prídem si po teba.",
  "prof.uredi": "Upraviť profil",
  "prof.arhiv": "Archív",
  "prof.objave": "Príspevky",
  "prof.shranjeno": "Uložené",
  "prof.oznaceno": "Označené",
  "prof.razporeditev": "Rozloženie",

  "gal.razpored.tri": "Tri stĺpce",
  "gal.razpored.dve": "Dva stĺpce",
  "gal.razpored.stiri": "Štyri stĺpce",
  "gal.razpored.mozaik": "Mozaika",
  "gal.razpored.stopnice": "Schody",
  "gal.razpored.gost": "Husto (6–7)",
  "gal.razpored.trak": "Pás",
  "gal.razpored.izvirno": "Pôvodné pomery",
  "gal.razpored.izvirnoxl": "Pôvodné pomery XL",
  "gal.razpored.polno": "Celá obrazovka",
  "gal.razpored.stolpci": "Tehly",
  "gal.razpored.prostor": "3D priestor",
  "gal.prostor.priblizaj": "Priblížiť",
  "gal.prostor.oddalji": "Oddialiť",
  "gal.razmik.da": "S medzerou",
  "gal.razmik.ne": "Bez medzery",
  "gal.sirina.robovi": "Až po okraje",
  "gal.sirina.cez": "Široko",
  "gal.sirina.sredina": "V strede",
};
