/** Српски - vmesnik. Besedila strani ostanejo slovenska, dokler niso prevedena. */
export default {
  "jezik.naslov": "Језик",
  "profil.aria": "Профил",
  "meni.aria": "Главни мени",
  "meni.arhiv": "Архива",
  "meni.delo": "Рад",
  "meni.omeni": "О мени",
  "meni.stik": "Контакт",
  "orodja.aria": "Алати",
  "orodja.iskanje": "Претрага",
  "orodja.nastavitve": "Подешавања",
  "orodja.arkada": "Аркада",

  "nast.naslov": "Подешавања",
  "nast.nazaj": "Назад",
  "nast.zapri": "Затвори",
  "nast.videz": "Изглед",
  "nast.jezik": "Језик",
  "nast.prosojnost": "Провидност",
  "nast.tema": "Тема",
  "nast.temna": "Тамна",
  "nast.svetla": "Светла",
  "nast.sistem": "Према систему",
  "nast.ozadje": "Позадина",
  "nast.prizor": "Призор",
  "nast.galaksija": "Галаксија",
  "nast.zvezde": "Само звезде",
  "nast.izklop": "Искључено",
  "nast.daljna": "Удаљена галаксија",
  "nast.daljnaOpis": "Друга галаксија у позадини",
  "nast.galaksijaOpis": "Сјај, величина звезда, брзина",
  "nast.gibanje": "Кретање",
  "nast.odziv": "Одзив на миш",
  "nast.odzivOpis": "Поглед прати показивач",
  "nast.kazalec": "Показивач",
  "nast.kazalecMeri": "Сопствени показивач",
  "nast.kazalecMeriOpis": "Искра уместо системског показивача",
  "nast.magnet": "Магнетни дугмићи",
  "nast.magnetOpis": "Дугмићи се нагињу ка показивачу",
  "nast.izris": "Исцртавање",
  "nast.sij": "Сјај",
  "nast.velikost": "Величина звезда",
  "nast.kamera": "Камера",
  "nast.hitrost": "Брзина орбите",

  "zapis.zapri": "Затвори",
  "zapis.prejsnja": "Претходна",
  "zapis.naslednja": "Следећа",
  "zapis.odpri": "Отвори апликацију",
  "zapis.seVec": "и још",
  "aplikacija.demo": "Демо верзија · подаци су измишљени",
  "aplikacija.zavihek": "Отвори у новој картици",
  "aplikacija.zapri": "Затвори апликацију",

  "viz.stran": "САЈТ",
  "viz.prizor": "ПРИЗОР",
  "viz.prizorV": "галаксија, 50 000 тачака",
  "viz.izris": "ИСЦРТАВАЊЕ",
  "viz.izrisV": "WebGL, сопствени шејдер",
  "viz.ogrodje": "ОКВИР",
  "viz.ogrodjeV": "Vite, без оквира",
  "viz.galerija": "ГАЛЕРИЈА",
  "viz.objav": "објава",
  "viz.maskota": "Маскота Jure Labs",
  "viz.zapri": "Затвори визиткарту",
  "viz.ascii": "ASCII анимација Jure Labs",
  "viz.metaT": "Веб апликације по мери",
  "viz.metaS": "Брзе. Поуздане. Ефикасне.",

  "kmeni.novZavihek": "Отвори у новој картици",
  "kmeni.kopiraj": "Копирај адресу",
  "kmeni.profil": "Профил",
  "kmeni.nastavitve": "Подешавања",
  "kmeni.ponastavi": "Врати поглед",
  "kmeni.kopirajBesedilo": "Копирај",
  "kmeni.kopirajPovezavo": "Копирај везу",
  "kmeni.kopirajEposto": "Копирај адресу е-поште",
  "kmeni.odpriSliko": "Отвори слику",
  "kmeni.kopirajSliko": "Копирај адресу слике",
  "kmeni.jezik": "Језик",
  "kmeni.kopirajStran": "Копирај везу странице",
  "kmeni.celozaslonsko": "Цео екран",
  "kmeni.izhodCelozaslonsko": "Изађи из целог екрана",
  "arkada.naslov": "Аркада",
  "arkada.kmalu": "Ускоро",
  "arkada.opis": "Мини игре су у изради. Ускоро ћеш моћи да их играш баш овде.",

  "ogled.zapri": "Затвори слику",
  "zemlja.slovenija": "Словенија",

  "prof.zapri": "Затвори",
  "prof.objav": "објава",
  "prof.sledilcev": "пратилаца",
  "prof.sledi": "прати",
  "prof.bio": "✨ Ако не ухватим звезде, доћи ћу по тебе.",
  "prof.uredi": "Уреди профил",
  "prof.arhiv": "Архива",
  "prof.objave": "Објаве",
  "prof.shranjeno": "Сачувано",
  "prof.oznaceno": "Означено",
  "prof.razporeditev": "Распоред",

  "gal.razpored.tri": "Три колоне",
  "gal.razpored.dve": "Две колоне",
  "gal.razpored.stiri": "Четири колоне",
  "gal.razpored.mozaik": "Мозаик",
  "gal.razpored.stopnice": "Степенице",
  "gal.razpored.gost": "Густо (6–7)",
  "gal.razpored.trak": "Трака",
  "gal.razpored.izvirno": "Изворне размере",
  "gal.razpored.izvirnoxl": "Изворне размере XL",
  "gal.razpored.polno": "Цео екран",
  "gal.razpored.stolpci": "Цигле",
  "gal.razpored.prostor": "3Д простор",
  "gal.prostor.priblizaj": "Приближи",
  "gal.prostor.oddalji": "Удаљи",
  "gal.razmik.da": "Са размаком",
  "gal.razmik.ne": "Без размака",
  "gal.sirina.robovi": "До ивица",
  "gal.sirina.cez": "Широко",
  "gal.sirina.sredina": "У средини",
};
