/** Svenska - vmesnik. Besedila strani ostanejo slovenska, dokler niso prevedena. */
export default {
  "jezik.naslov": "Språk",
  "profil.aria": "Profil",
  "meni.aria": "Huvudmeny",
  "meni.arhiv": "Arkiv",
  "meni.delo": "Arbete",
  "meni.omeni": "Om mig",
  "meni.stik": "Kontakt",
  "orodja.aria": "Verktyg",
  "orodja.iskanje": "Sök",
  "orodja.nastavitve": "Inställningar",

  "nast.naslov": "Inställningar",
  "nast.nazaj": "Tillbaka",
  "nast.zapri": "Stäng",
  "nast.videz": "Utseende",
  "nast.jezik": "Språk",
  "nast.prosojnost": "Genomskinlighet",
  "nast.tema": "Tema",
  "nast.temna": "Mörkt",
  "nast.svetla": "Ljust",
  "nast.sistem": "System",
  "nast.ozadje": "Bakgrund",
  "nast.prizor": "Scen",
  "nast.galaksija": "Galax",
  "nast.zvezde": "Bara stjärnor",
  "nast.izklop": "Av",
  "nast.daljna": "Avlägsen galax",
  "nast.daljnaOpis": "En andra galax i bakgrunden",
  "nast.galaksijaOpis": "Glöd, stjärnstorlek, hastighet",
  "nast.gibanje": "Rörelse",
  "nast.odziv": "Musrespons",
  "nast.odzivOpis": "Vyn följer markören",
  "nast.kazalec": "Markör",
  "nast.kazalecMeri": "Egen markör",
  "nast.kazalecMeriOpis": "En gnista i stället för systemmarkören",
  "nast.magnet": "Magnetiska knappar",
  "nast.magnetOpis": "Knapparna lutar sig mot markören",
  "nast.izris": "Rendering",
  "nast.sij": "Glöd",
  "nast.velikost": "Stjärnstorlek",
  "nast.kamera": "Kamera",
  "nast.hitrost": "Omloppshastighet",

  "zapis.zapri": "Stäng",
  "zapis.prejsnja": "Föregående",
  "zapis.naslednja": "Nästa",

  "viz.stran": "WEBBPLATS",
  "viz.prizor": "SCEN",
  "viz.prizorV": "galax, 50 000 punkter",
  "viz.izris": "RENDERING",
  "viz.izrisV": "WebGL, egen shader",
  "viz.ogrodje": "RAMVERK",
  "viz.ogrodjeV": "Vite, utan ramverk",
  "viz.galerija": "GALLERI",
  "viz.objav": "inlägg",
  "viz.maskota": "Jure Labs maskot",
  "viz.zapri": "Stäng visitkortet",
  "viz.ascii": "Jure Labs ASCII-animation",
  "viz.metaT": "Skräddarsydda webbappar",
  "viz.metaS": "Snabba. Pålitliga. Effektiva.",

  "kmeni.novZavihek": "Öppna i ny flik",
  "kmeni.kopiraj": "Kopiera adress",
  "kmeni.profil": "Profil",
  "kmeni.nastavitve": "Inställningar",
  "kmeni.ponastavi": "Återställ vyn",

  "ogled.zapri": "Stäng bilden",
  "zemlja.slovenija": "Slovenien",

  "prof.zapri": "Stäng",
  "prof.objav": "inlägg",
  "prof.sledilcev": "följare",
  "prof.sledi": "följer",
  "prof.bio": "✨ Om jag inte fångar stjärnorna kommer jag efter dig.",
  "prof.uredi": "Redigera profil",
  "prof.arhiv": "Arkiv",
  "prof.objave": "Inlägg",
  "prof.shranjeno": "Sparat",
  "prof.oznaceno": "Taggat",
  "prof.razporeditev": "Layout",

  "gal.razpored.tri": "Tre kolumner",
  "gal.razpored.dve": "Två kolumner",
  "gal.razpored.stiri": "Fyra kolumner",
  "gal.razpored.mozaik": "Mosaik",
  "gal.razpored.stopnice": "Trappsteg",
  "gal.razpored.gost": "Tätt (6–7)",
  "gal.razpored.trak": "Remsa",
  "gal.razpored.izvirno": "Originalproportioner",
  "gal.razpored.izvirnoxl": "Originalproportioner XL",
  "gal.razpored.polno": "Helskärm",
  "gal.razpored.stolpci": "Tegel",
  "gal.razmik.da": "Med mellanrum",
  "gal.razmik.ne": "Utan mellanrum",
  "gal.sirina.robovi": "Kant till kant",
  "gal.sirina.cez": "Brett",
  "gal.sirina.sredina": "Centrerat",
};
