/** Türkçe - vmesnik. Besedila strani ostanejo slovenska, dokler niso prevedena. */
export default {
  "jezik.naslov": "Dil",
  "profil.aria": "Profil",
  "meni.aria": "Ana menü",
  "meni.arhiv": "Arşiv",
  "meni.delo": "İş",
  "meni.omeni": "Hakkımda",
  "meni.stik": "İletişim",
  "orodja.aria": "Araçlar",
  "orodja.iskanje": "Ara",
  "orodja.nastavitve": "Ayarlar",

  "nast.naslov": "Ayarlar",
  "nast.nazaj": "Geri",
  "nast.zapri": "Kapat",
  "nast.videz": "Görünüm",
  "nast.jezik": "Dil",
  "nast.prosojnost": "Saydamlık",
  "nast.tema": "Tema",
  "nast.temna": "Koyu",
  "nast.svetla": "Açık",
  "nast.sistem": "Sistem",
  "nast.ozadje": "Arka plan",
  "nast.prizor": "Sahne",
  "nast.galaksija": "Galaksi",
  "nast.zvezde": "Yalnızca yıldızlar",
  "nast.izklop": "Kapalı",
  "nast.daljna": "Uzak galaksi",
  "nast.daljnaOpis": "Arka planda ikinci bir galaksi",
  "nast.galaksijaOpis": "Parıltı, yıldız boyutu, hız",
  "nast.gibanje": "Hareket",
  "nast.odziv": "Fare tepkisi",
  "nast.odzivOpis": "Görünüm imleci takip eder",
  "nast.kazalec": "İmleç",
  "nast.kazalecMeri": "Özel imleç",
  "nast.kazalecMeriOpis": "Sistem imleci yerine bir kıvılcım",
  "nast.magnet": "Manyetik düğmeler",
  "nast.magnetOpis": "Düğmeler imlece doğru eğilir",
  "nast.izris": "İşleme",
  "nast.sij": "Parıltı",
  "nast.velikost": "Yıldız boyutu",
  "nast.kamera": "Kamera",
  "nast.hitrost": "Yörünge hızı",

  "zapis.zapri": "Kapat",
  "zapis.prejsnja": "Önceki",
  "zapis.naslednja": "Sonraki",
  "zapis.odpri": "Uygulamayı aç",
  "aplikacija.demo": "Demo sürümü · veriler uydurmadır",
  "aplikacija.zavihek": "Yeni sekmede aç",
  "aplikacija.zapri": "Uygulamayı kapat",

  "viz.stran": "SİTE",
  "viz.prizor": "SAHNE",
  "viz.prizorV": "galaksi, 50.000 nokta",
  "viz.izris": "İŞLEME",
  "viz.izrisV": "WebGL, özel shader",
  "viz.ogrodje": "ÇERÇEVE",
  "viz.ogrodjeV": "Vite, çerçevesiz",
  "viz.galerija": "GALERİ",
  "viz.objav": "gönderi",
  "viz.maskota": "Jure Labs maskotu",
  "viz.zapri": "Kartviziti kapat",
  "viz.ascii": "Jure Labs ASCII animasyonu",
  "viz.metaT": "Özel web uygulamaları",
  "viz.metaS": "Hızlı. Güvenilir. Verimli.",

  "kmeni.novZavihek": "Yeni sekmede aç",
  "kmeni.kopiraj": "Adresi kopyala",
  "kmeni.profil": "Profil",
  "kmeni.nastavitve": "Ayarlar",
  "kmeni.ponastavi": "Görünümü sıfırla",

  "ogled.zapri": "Görseli kapat",
  "zemlja.slovenija": "Slovenya",

  "prof.zapri": "Kapat",
  "prof.objav": "gönderi",
  "prof.sledilcev": "takipçi",
  "prof.sledi": "takip",
  "prof.bio": "✨ Yıldızları yakalayamazsam senin için gelirim.",
  "prof.uredi": "Profili düzenle",
  "prof.arhiv": "Arşiv",
  "prof.objave": "Gönderiler",
  "prof.shranjeno": "Kaydedilenler",
  "prof.oznaceno": "Etiketlenenler",
  "prof.razporeditev": "Düzen",

  "gal.razpored.tri": "Üç sütun",
  "gal.razpored.dve": "İki sütun",
  "gal.razpored.stiri": "Dört sütun",
  "gal.razpored.mozaik": "Mozaik",
  "gal.razpored.stopnice": "Basamaklar",
  "gal.razpored.gost": "Yoğun (6–7)",
  "gal.razpored.trak": "Şerit",
  "gal.razpored.izvirno": "Orijinal oranlar",
  "gal.razpored.izvirnoxl": "Orijinal oranlar XL",
  "gal.razpored.polno": "Tam ekran",
  "gal.razpored.stolpci": "Tuğla",
  "gal.razpored.prostor": "3B alan",
  "gal.prostor.priblizaj": "Yakınlaştır",
  "gal.prostor.oddalji": "Uzaklaştır",
  "gal.razmik.da": "Boşluklu",
  "gal.razmik.ne": "Boşluksuz",
  "gal.sirina.robovi": "Kenardan kenara",
  "gal.sirina.cez": "Geniş",
  "gal.sirina.sredina": "Ortalanmış",
};
