/** Українська - vmesnik. Besedila strani ostanejo slovenska, dokler niso prevedena. */
export default {
  "jezik.naslov": "Мова",
  "profil.aria": "Профіль",
  "meni.aria": "Головне меню",
  "meni.arhiv": "Архів",
  "meni.delo": "Робота",
  "meni.omeni": "Про мене",
  "meni.stik": "Контакт",
  "orodja.aria": "Інструменти",
  "orodja.iskanje": "Пошук",
  "orodja.nastavitve": "Налаштування",

  "nast.naslov": "Налаштування",
  "nast.nazaj": "Назад",
  "nast.zapri": "Закрити",
  "nast.videz": "Вигляд",
  "nast.jezik": "Мова",
  "nast.prosojnost": "Прозорість",
  "nast.tema": "Тема",
  "nast.temna": "Темна",
  "nast.svetla": "Світла",
  "nast.sistem": "Як у системі",
  "nast.ozadje": "Тло",
  "nast.prizor": "Сцена",
  "nast.galaksija": "Галактика",
  "nast.zvezde": "Лише зорі",
  "nast.izklop": "Вимкнено",
  "nast.daljna": "Далека галактика",
  "nast.daljnaOpis": "Друга галактика на тлі",
  "nast.galaksijaOpis": "Сяйво, розмір зір, швидкість",
  "nast.gibanje": "Рух",
  "nast.odziv": "Реакція на мишу",
  "nast.odzivOpis": "Вигляд стежить за курсором",
  "nast.kazalec": "Курсор",
  "nast.kazalecMeri": "Власний курсор",
  "nast.kazalecMeriOpis": "Іскра замість системного курсора",
  "nast.magnet": "Магнітні кнопки",
  "nast.magnetOpis": "Кнопки нахиляються до курсора",
  "nast.izris": "Рендеринг",
  "nast.sij": "Сяйво",
  "nast.velikost": "Розмір зір",
  "nast.kamera": "Камера",
  "nast.hitrost": "Швидкість орбіти",

  "zapis.zapri": "Закрити",
  "zapis.prejsnja": "Попередня",
  "zapis.naslednja": "Наступна",

  "viz.stran": "САЙТ",
  "viz.prizor": "СЦЕНА",
  "viz.prizorV": "галактика, 50 000 точок",
  "viz.izris": "РЕНДЕРИНГ",
  "viz.izrisV": "WebGL, власний шейдер",
  "viz.ogrodje": "ФРЕЙМВОРК",
  "viz.ogrodjeV": "Vite, без фреймворку",
  "viz.galerija": "ГАЛЕРЕЯ",
  "viz.objav": "дописів",
  "viz.maskota": "Талісман Jure Labs",
  "viz.zapri": "Закрити візитівку",
  "viz.ascii": "ASCII-анімація Jure Labs",
  "viz.metaT": "Вебзастосунки на замовлення",
  "viz.metaS": "Швидкі. Надійні. Ефективні.",

  "kmeni.novZavihek": "Відкрити в новій вкладці",
  "kmeni.kopiraj": "Копіювати адресу",
  "kmeni.profil": "Профіль",
  "kmeni.nastavitve": "Налаштування",
  "kmeni.ponastavi": "Скинути вигляд",

  "ogled.zapri": "Закрити зображення",
  "zemlja.slovenija": "Словенія",

  "prof.zapri": "Закрити",
  "prof.objav": "дописів",
  "prof.sledilcev": "підписників",
  "prof.sledi": "стежить",
  "prof.bio": "✨ Якщо не впіймаю зорі, прийду по тебе.",
  "prof.uredi": "Редагувати профіль",
  "prof.arhiv": "Архів",
  "prof.objave": "Дописи",
  "prof.shranjeno": "Збережене",
  "prof.oznaceno": "Позначки",
  "prof.razporeditev": "Макет",

  "gal.razpored.tri": "Три стовпці",
  "gal.razpored.dve": "Два стовпці",
  "gal.razpored.stiri": "Чотири стовпці",
  "gal.razpored.mozaik": "Мозаїка",
  "gal.razpored.stopnice": "Сходинки",
  "gal.razpored.gost": "Щільно (6–7)",
  "gal.razpored.trak": "Стрічка",
  "gal.razpored.izvirno": "Оригінальні пропорції",
  "gal.razpored.izvirnoxl": "Оригінальні пропорції XL",
  "gal.razpored.polno": "На весь екран",
  "gal.razpored.stolpci": "Цегла",
  "gal.razpored.prostor": "3D-простір",
  "gal.prostor.priblizaj": "Наблизити",
  "gal.prostor.oddalji": "Віддалити",
  "gal.razmik.da": "З відступом",
  "gal.razmik.ne": "Без відступу",
  "gal.sirina.robovi": "До країв",
  "gal.sirina.cez": "Широко",
  "gal.sirina.sredina": "По центру",
};
