/** 中文 - vmesnik. Besedila strani ostanejo slovenska, dokler niso prevedena. */
export default {
  "jezik.naslov": "语言",
  "profil.aria": "个人资料",
  "meni.aria": "主菜单",
  "meni.arhiv": "归档",
  "meni.delo": "作品",
  "meni.omeni": "关于我",
  "meni.stik": "联系",
  "orodja.aria": "工具",
  "orodja.iskanje": "搜索",
  "orodja.nastavitve": "设置",
  "orodja.arkada": "游戏厅",

  "nast.naslov": "设置",
  "nast.nazaj": "返回",
  "nast.zapri": "关闭",
  "nast.videz": "外观",
  "nast.jezik": "语言",
  "nast.prosojnost": "透明度",
  "nast.tema": "主题",
  "nast.temna": "深色",
  "nast.svetla": "浅色",
  "nast.sistem": "跟随系统",
  "nast.ozadje": "背景",
  "nast.prizor": "场景",
  "nast.galaksija": "星系",
  "nast.zvezde": "仅星星",
  "nast.izklop": "关闭",
  "nast.daljna": "远方星系",
  "nast.daljnaOpis": "背景中的第二个星系",
  "nast.galaksijaOpis": "光晕、星星大小、速度",
  "nast.gibanje": "动态",
  "nast.odziv": "鼠标响应",
  "nast.odzivOpis": "视角跟随光标",
  "nast.kazalec": "光标",
  "nast.kazalecMeri": "自定义光标",
  "nast.kazalecMeriOpis": "用火花代替系统光标",
  "nast.magnet": "磁性按钮",
  "nast.magnetOpis": "按钮向光标倾斜",
  "nast.izris": "渲染",
  "nast.sij": "光晕",
  "nast.velikost": "星星大小",
  "nast.kamera": "相机",
  "nast.hitrost": "轨道速度",

  "zapis.zapri": "关闭",
  "zapis.prejsnja": "上一张",
  "zapis.naslednja": "下一张",
  "zapis.odpri": "打开应用",
  "zapis.seVec": "等等",
  "aplikacija.demo": "演示版 · 数据为虚构",
  "aplikacija.zavihek": "在新标签页中打开",
  "aplikacija.zapri": "关闭应用",

  "viz.stran": "网站",
  "viz.prizor": "场景",
  "viz.prizorV": "星系，50,000 个点",
  "viz.izris": "渲染",
  "viz.izrisV": "WebGL，自写着色器",
  "viz.ogrodje": "框架",
  "viz.ogrodjeV": "Vite，无框架",
  "viz.galerija": "图库",
  "viz.objav": "帖子",
  "viz.maskota": "Jure Labs 吉祥物",
  "viz.zapri": "关闭名片",
  "viz.ascii": "Jure Labs ASCII 动画",
  "viz.metaT": "定制网页应用",
  "viz.metaS": "快速。可靠。高效。",

  "kmeni.novZavihek": "在新标签页中打开",
  "kmeni.kopiraj": "复制地址",
  "kmeni.profil": "个人资料",
  "kmeni.nastavitve": "设置",
  "kmeni.ponastavi": "重置视图",
  "kmeni.kopirajBesedilo": "复制",
  "kmeni.kopirajPovezavo": "复制链接",
  "kmeni.kopirajEposto": "复制电子邮件地址",
  "kmeni.odpriSliko": "打开图片",
  "kmeni.kopirajSliko": "复制图片地址",
  "kmeni.jezik": "语言",
  "kmeni.kopirajStran": "复制页面链接",
  "kmeni.celozaslonsko": "全屏",
  "kmeni.izhodCelozaslonsko": "退出全屏",
  "arkada.naslov": "游戏厅",
  "arkada.kmalu": "即将推出",
  "arkada.opis": "小游戏正在制作中，很快就能在这里玩了。",

  "ogled.zapri": "关闭图片",
  "zemlja.slovenija": "斯洛文尼亚",

  "prof.zapri": "关闭",
  "prof.objav": "帖子",
  "prof.sledilcev": "粉丝",
  "prof.sledi": "关注",
  "prof.uredi": "编辑资料",
  "prof.arhiv": "归档",
  "prof.objave": "帖子",
  "prof.shranjeno": "已保存",
  "prof.oznaceno": "被标记",
  "prof.razporeditev": "布局",

  "gal.razpored.tri": "三列",
  "gal.razpored.dve": "两列",
  "gal.razpored.stiri": "四列",
  "gal.razpored.mozaik": "马赛克",
  "gal.razpored.stopnice": "阶梯",
  "gal.razpored.gost": "密集 (6–7)",
  "gal.razpored.trak": "长条",
  "gal.razpored.izvirno": "原始比例",
  "gal.razpored.izvirnoxl": "原始比例 XL",
  "gal.razpored.polno": "全屏",
  "gal.razpored.stolpci": "砖墙",
  "gal.razpored.prostor": "3D 空间",
  "gal.prostor.priblizaj": "放大",
  "gal.prostor.oddalji": "缩小",
  "gal.razmik.da": "有间距",
  "gal.razmik.ne": "无间距",
  "gal.sirina.robovi": "铺满边缘",
  "gal.sirina.cez": "宽",
  "gal.sirina.sredina": "居中",
};
